// airports.ts
// Static airport data for autocomplete — IATA code + city + country.
// Codes sourced from airport_codes.py (backend validator).
// Place at: RewardWise_MVP0/Frontend/lib/airports.ts

export interface Airport {
  code: string;
  city: string;
  country: string;
  name?: string;
}

export const AIRPORTS: Airport[] = [
  // ── United States ──────────────────────────────────────────────────────────
  { code: "ATL", city: "Atlanta", country: "US", name: "Hartsfield-Jackson" },
  { code: "LAX", city: "Los Angeles", country: "US", name: "Los Angeles Intl" },
  { code: "ORD", city: "Chicago", country: "US", name: "O'Hare Intl" },
  { code: "DFW", city: "Dallas", country: "US", name: "Dallas/Fort Worth" },
  { code: "DEN", city: "Denver", country: "US", name: "Denver Intl" },
  { code: "JFK", city: "New York", country: "US", name: "John F. Kennedy" },
  { code: "SFO", city: "San Francisco", country: "US", name: "San Francisco Intl" },
  { code: "SEA", city: "Seattle", country: "US", name: "Seattle-Tacoma" },
  { code: "LAS", city: "Las Vegas", country: "US", name: "Harry Reid Intl" },
  { code: "MCO", city: "Orlando", country: "US", name: "Orlando Intl" },
  { code: "EWR", city: "Newark", country: "US", name: "Newark Liberty" },
  { code: "CLT", city: "Charlotte", country: "US", name: "Charlotte Douglas" },
  { code: "PHX", city: "Phoenix", country: "US", name: "Phoenix Sky Harbor" },
  { code: "IAH", city: "Houston", country: "US", name: "George Bush" },
  { code: "MIA", city: "Miami", country: "US", name: "Miami Intl" },
  { code: "BOS", city: "Boston", country: "US", name: "Logan Intl" },
  { code: "MSP", city: "Minneapolis", country: "US", name: "Minneapolis-St. Paul" },
  { code: "FLL", city: "Fort Lauderdale", country: "US", name: "Fort Lauderdale-Hollywood" },
  { code: "DTW", city: "Detroit", country: "US", name: "Detroit Metropolitan" },
  { code: "PHL", city: "Philadelphia", country: "US", name: "Philadelphia Intl" },
  { code: "LGA", city: "New York", country: "US", name: "LaGuardia" },
  { code: "BWI", city: "Baltimore", country: "US", name: "Baltimore/Washington" },
  { code: "SLC", city: "Salt Lake City", country: "US", name: "Salt Lake City Intl" },
  { code: "DCA", city: "Washington", country: "US", name: "Ronald Reagan" },
  { code: "SAN", city: "San Diego", country: "US", name: "San Diego Intl" },
  { code: "MDW", city: "Chicago", country: "US", name: "Midway" },
  { code: "TPA", city: "Tampa", country: "US", name: "Tampa Intl" },
  { code: "PDX", city: "Portland", country: "US", name: "Portland Intl" },
  { code: "HNL", city: "Honolulu", country: "US", name: "Daniel K. Inouye" },
  { code: "DAL", city: "Dallas", country: "US", name: "Love Field" },
  { code: "STL", city: "St. Louis", country: "US", name: "Lambert Intl" },
  { code: "BNA", city: "Nashville", country: "US", name: "Nashville Intl" },
  { code: "OAK", city: "Oakland", country: "US", name: "Oakland Intl" },
  { code: "AUS", city: "Austin", country: "US", name: "Austin-Bergstrom" },
  { code: "MCI", city: "Kansas City", country: "US", name: "Kansas City Intl" },
  { code: "RDU", city: "Raleigh", country: "US", name: "Raleigh-Durham" },
  { code: "SJC", city: "San Jose", country: "US", name: "San Jose Intl" },
  { code: "SMF", city: "Sacramento", country: "US", name: "Sacramento Intl" },
  { code: "IAD", city: "Washington", country: "US", name: "Dulles Intl" },
  { code: "MSY", city: "New Orleans", country: "US", name: "Louis Armstrong" },
  { code: "SNA", city: "Santa Ana", country: "US", name: "John Wayne" },
  { code: "RSW", city: "Fort Myers", country: "US", name: "Southwest Florida" },
  { code: "MKE", city: "Milwaukee", country: "US", name: "General Mitchell" },
  { code: "PIT", city: "Pittsburgh", country: "US", name: "Pittsburgh Intl" },
  { code: "CMH", city: "Columbus", country: "US", name: "John Glenn" },
  { code: "SAT", city: "San Antonio", country: "US", name: "San Antonio Intl" },
  { code: "IND", city: "Indianapolis", country: "US", name: "Indianapolis Intl" },
  { code: "ABQ", city: "Albuquerque", country: "US", name: "Albuquerque Intl Sunport" },
  { code: "BDL", city: "Hartford", country: "US", name: "Bradley Intl" },
  { code: "BUF", city: "Buffalo", country: "US", name: "Buffalo Niagara" },
  { code: "CLE", city: "Cleveland", country: "US", name: "Cleveland Hopkins" },
  { code: "MEM", city: "Memphis", country: "US", name: "Memphis Intl" },
  { code: "JAX", city: "Jacksonville", country: "US", name: "Jacksonville Intl" },
  { code: "PBI", city: "West Palm Beach", country: "US", name: "Palm Beach Intl" },
  { code: "ANC", city: "Anchorage", country: "US", name: "Ted Stevens" },
  { code: "BOI", city: "Boise", country: "US", name: "Boise Airport" },
  { code: "TUS", city: "Tucson", country: "US", name: "Tucson Intl" },
  { code: "ELP", city: "El Paso", country: "US", name: "El Paso Intl" },
  { code: "OMA", city: "Omaha", country: "US", name: "Eppley Airfield" },
  { code: "TUL", city: "Tulsa", country: "US", name: "Tulsa Intl" },
  { code: "OKC", city: "Oklahoma City", country: "US", name: "Will Rogers World" },
  { code: "SJU", city: "San Juan", country: "US", name: "Luis Muñoz Marín" },
  { code: "GEG", city: "Spokane", country: "US", name: "Spokane Intl" },
  { code: "SDF", city: "Louisville", country: "US", name: "Louisville Intl" },
  { code: "CVG", city: "Cincinnati", country: "US", name: "Cincinnati/Northern Kentucky" },
  { code: "RNO", city: "Reno", country: "US", name: "Reno-Tahoe" },
  { code: "LIH", city: "Lihue", country: "US", name: "Lihue Airport" },
  { code: "OGG", city: "Maui", country: "US", name: "Kahului Airport" },
  { code: "KOA", city: "Kona", country: "US", name: "Ellison Onizuka Kona" },
  { code: "ITO", city: "Hilo", country: "US", name: "Hilo Intl" },
  { code: "FAI", city: "Fairbanks", country: "US", name: "Fairbanks Intl" },
  { code: "JNU", city: "Juneau", country: "US", name: "Juneau Intl" },
  { code: "HPN", city: "White Plains", country: "US", name: "Westchester County" },
  { code: "ISP", city: "Islip", country: "US", name: "Long Island MacArthur" },
  { code: "ACY", city: "Atlantic City", country: "US", name: "Atlantic City Intl" },
  { code: "TYS", city: "Knoxville", country: "US", name: "McGhee Tyson" },
  { code: "AVL", city: "Asheville", country: "US", name: "Asheville Regional" },
  { code: "GSO", city: "Greensboro", country: "US", name: "Piedmont Triad" },
  { code: "ILM", city: "Wilmington", country: "US", name: "Wilmington Intl" },
  { code: "CAE", city: "Columbia", country: "US", name: "Columbia Metropolitan" },
  { code: "CHS", city: "Charleston", country: "US", name: "Charleston Intl" },
  { code: "SAV", city: "Savannah", country: "US", name: "Savannah/Hilton Head" },
  { code: "MYR", city: "Myrtle Beach", country: "US", name: "Myrtle Beach Intl" },
  { code: "GNV", city: "Gainesville", country: "US", name: "Gainesville Regional" },
  { code: "EYW", city: "Key West", country: "US", name: "Key West Intl" },
  { code: "DAB", city: "Daytona Beach", country: "US", name: "Daytona Beach Intl" },
  { code: "SRQ", city: "Sarasota", country: "US", name: "Sarasota-Bradenton" },
  { code: "PIE", city: "St. Petersburg", country: "US", name: "St. Pete-Clearwater" },
  { code: "VPS", city: "Destin", country: "US", name: "Destin-Fort Walton Beach" },
  { code: "COS", city: "Colorado Springs", country: "US", name: "Colorado Springs" },
  { code: "ASE", city: "Aspen", country: "US", name: "Aspen/Pitkin County" },
  { code: "HDN", city: "Steamboat Springs", country: "US", name: "Yampa Valley" },
  { code: "MTJ", city: "Montrose", country: "US", name: "Montrose Regional" },
  { code: "GJT", city: "Grand Junction", country: "US", name: "Grand Junction Regional" },
  { code: "JAC", city: "Jackson Hole", country: "US", name: "Jackson Hole Airport" },
  { code: "BZN", city: "Bozeman", country: "US", name: "Bozeman Yellowstone" },
  { code: "MSN", city: "Madison", country: "US", name: "Dane County Regional" },
  { code: "GRR", city: "Grand Rapids", country: "US", name: "Gerald R. Ford" },
  { code: "FSD", city: "Sioux Falls", country: "US", name: "Sioux Falls Regional" },
  { code: "DSM", city: "Des Moines", country: "US", name: "Des Moines Intl" },
  { code: "CID", city: "Cedar Rapids", country: "US", name: "Eastern Iowa Airport" },
  { code: "LAN", city: "Lansing", country: "US", name: "Capital Region Intl" },
  { code: "FNT", city: "Flint", country: "US", name: "Bishop Intl" },
  { code: "SHV", city: "Shreveport", country: "US", name: "Shreveport Regional" },
  { code: "BTR", city: "Baton Rouge", country: "US", name: "Baton Rouge Metropolitan" },
  { code: "LFT", city: "Lafayette", country: "US", name: "Lafayette Regional" },
  { code: "HOU", city: "Houston", country: "US", name: "William P. Hobby" },
  { code: "MAF", city: "Midland", country: "US", name: "Midland Intl" },
  { code: "LBB", city: "Lubbock", country: "US", name: "Lubbock Preston Smith" },
  { code: "AMA", city: "Amarillo", country: "US", name: "Rick Husband Amarillo" },
  { code: "CRP", city: "Corpus Christi", country: "US", name: "Corpus Christi Intl" },
  { code: "MFE", city: "McAllen", country: "US", name: "McAllen Miller Intl" },
  { code: "LRD", city: "Laredo", country: "US", name: "Laredo Intl" },
  { code: "LAW", city: "Lawton", country: "US", name: "Lawton-Fort Sill" },
  { code: "SGF", city: "Springfield", country: "US", name: "Springfield-Branson" },
  { code: "ROC", city: "Rochester", country: "US", name: "Frederick Douglass" },
  { code: "SYR", city: "Syracuse", country: "US", name: "Syracuse Hancock" },
  { code: "ALB", city: "Albany", country: "US", name: "Albany Intl" },
  { code: "BHM", city: "Birmingham", country: "US", name: "Birmingham-Shuttlesworth" },
  { code: "MOB", city: "Mobile", country: "US", name: "Mobile Regional" },
  { code: "HSV", city: "Huntsville", country: "US", name: "Huntsville Intl" },
  { code: "PNS", city: "Pensacola", country: "US", name: "Pensacola Intl" },
  { code: "GPT", city: "Gulfport", country: "US", name: "Gulfport-Biloxi" },
  { code: "LIT", city: "Little Rock", country: "US", name: "Clinton National" },
  { code: "MLU", city: "Monroe", country: "US", name: "Monroe Regional" },
  { code: "ICT", city: "Wichita", country: "US", name: "Dwight D. Eisenhower" },
  { code: "FAR", city: "Fargo", country: "US", name: "Hector Intl" },
  { code: "BIS", city: "Bismarck", country: "US", name: "Bismarck Municipal" },
  { code: "RAP", city: "Rapid City", country: "US", name: "Rapid City Regional" },
  { code: "MFR", city: "Medford", country: "US", name: "Rogue Valley Intl" },
  { code: "EUG", city: "Eugene", country: "US", name: "Eugene Airport" },
  { code: "RDM", city: "Bend", country: "US", name: "Redmond Airport" },
  { code: "SBA", city: "Santa Barbara", country: "US", name: "Santa Barbara Municipal" },
  { code: "FAT", city: "Fresno", country: "US", name: "Fresno Yosemite Intl" },
  { code: "MRY", city: "Monterey", country: "US", name: "Monterey Regional" },
  { code: "ACV", city: "Arcata", country: "US", name: "Arcata-Eureka" },
  { code: "BFL", city: "Bakersfield", country: "US", name: "Meadows Field" },
  { code: "TWF", city: "Twin Falls", country: "US", name: "Magic Valley Regional" },
  { code: "PIH", city: "Pocatello", country: "US", name: "Pocatello Regional" },
  { code: "LWS", city: "Lewiston", country: "US", name: "Lewiston-Nez Perce County" },
  { code: "GCC", city: "Gillette", country: "US", name: "Gillette-Campbell County" },
  { code: "CYS", city: "Cheyenne", country: "US", name: "Cheyenne Regional" },
  { code: "EGE", city: "Vail", country: "US", name: "Eagle County Regional" },
  { code: "GTF", city: "Great Falls", country: "US", name: "Great Falls Intl" },
  { code: "BIL", city: "Billings", country: "US", name: "Billings Logan Intl" },
  { code: "HLN", city: "Helena", country: "US", name: "Helena Regional" },
  { code: "GGW", city: "Glasgow", country: "US", name: "Glasgow Valley County" },
  { code: "CPR", city: "Casper", country: "US", name: "Casper-Natrona County" },
  { code: "MHT", city: "Manchester", country: "US", name: "Manchester-Boston Regional" },
  { code: "PVD", city: "Providence", country: "US", name: "T.F. Green" },
  { code: "PWM", city: "Portland", country: "US", name: "Portland Intl Jetport" },
  { code: "BTV", city: "Burlington", country: "US", name: "Burlington Intl" },
  { code: "BGR", city: "Bangor", country: "US", name: "Bangor Intl" },
  { code: "ORF", city: "Norfolk", country: "US", name: "Norfolk Intl" },
  { code: "RIC", city: "Richmond", country: "US", name: "Richmond Intl" },
  { code: "CHO", city: "Charlottesville", country: "US", name: "Charlottesville-Albemarle" },
  { code: "LYH", city: "Lynchburg", country: "US", name: "Lynchburg Regional" },
  { code: "MLB", city: "Melbourne", country: "US", name: "Melbourne Orlando Intl" },
  { code: "PHF", city: "Newport News", country: "US", name: "Newport News/Williamsburg" },
  { code: "ACK", city: "Nantucket", country: "US", name: "Nantucket Memorial" },
  { code: "MVY", city: "Martha's Vineyard", country: "US", name: "Martha's Vineyard" },
  { code: "HYA", city: "Hyannis", country: "US", name: "Barnstable Municipal" },
  { code: "OWD", city: "Norwood", country: "US", name: "Norwood Memorial" },

  // ── Canada ─────────────────────────────────────────────────────────────────
  { code: "YYZ", city: "Toronto", country: "CA", name: "Pearson Intl" },
  { code: "YVR", city: "Vancouver", country: "CA", name: "Vancouver Intl" },
  { code: "YUL", city: "Montreal", country: "CA", name: "Trudeau Intl" },
  { code: "YYC", city: "Calgary", country: "CA", name: "Calgary Intl" },
  { code: "YEG", city: "Edmonton", country: "CA", name: "Edmonton Intl" },
  { code: "YOW", city: "Ottawa", country: "CA", name: "Ottawa Macdonald-Cartier" },
  { code: "YHZ", city: "Halifax", country: "CA", name: "Stanfield Intl" },
  { code: "YWG", city: "Winnipeg", country: "CA", name: "Richardson Intl" },
  { code: "YQB", city: "Quebec City", country: "CA", name: "Jean Lesage Intl" },
  { code: "YYJ", city: "Victoria", country: "CA", name: "Victoria Intl" },
  { code: "YXE", city: "Saskatoon", country: "CA", name: "John G. Diefenbaker" },
  { code: "YQR", city: "Regina", country: "CA", name: "Regina Intl" },
  { code: "YQT", city: "Thunder Bay", country: "CA", name: "Thunder Bay Intl" },
  { code: "YXU", city: "London", country: "CA", name: "London Intl" },
  { code: "YTZ", city: "Toronto", country: "CA", name: "Billy Bishop" },
  { code: "YLW", city: "Kelowna", country: "CA", name: "Kelowna Intl" },
  { code: "YZF", city: "Yellowknife", country: "CA", name: "Yellowknife Airport" },
  { code: "YYT", city: "St. John's", country: "CA", name: "St. John's Intl" },
  { code: "YQM", city: "Moncton", country: "CA", name: "Greater Moncton" },
  { code: "YSJ", city: "Saint John", country: "CA", name: "Saint John Airport" },
  { code: "YFC", city: "Fredericton", country: "CA", name: "Fredericton Intl" },
  { code: "YMM", city: "Fort McMurray", country: "CA", name: "Fort McMurray Intl" },
  { code: "YDF", city: "Deer Lake", country: "CA", name: "Deer Lake Regional" },
  { code: "YGP", city: "Gaspe", country: "CA", name: "Michel-Pouliot Gaspé" },

  // ── Mexico ─────────────────────────────────────────────────────────────────
  { code: "MEX", city: "Mexico City", country: "MX", name: "Benito Juárez Intl" },
  { code: "CUN", city: "Cancun", country: "MX", name: "Cancún Intl" },
  { code: "GDL", city: "Guadalajara", country: "MX", name: "Don Miguel Hidalgo" },
  { code: "MTY", city: "Monterrey", country: "MX", name: "General Mariano Escobedo" },
  { code: "TIJ", city: "Tijuana", country: "MX", name: "General Abelardo Rodríguez" },
  { code: "SJD", city: "Los Cabos", country: "MX", name: "Los Cabos Intl" },
  { code: "MID", city: "Merida", country: "MX", name: "Manuel Crescencio Rejón" },
  { code: "PVR", city: "Puerto Vallarta", country: "MX", name: "Licenciado Gustavo Díaz Ordaz" },
  { code: "MZT", city: "Mazatlán", country: "MX", name: "General Rafael Buelna" },
  { code: "OAX", city: "Oaxaca", country: "MX", name: "Xoxocotlán Intl" },
  { code: "HUX", city: "Huatulco", country: "MX", name: "Bahías de Huatulco" },
  { code: "ZIH", city: "Zihuatanejo", country: "MX", name: "Ixtapa-Zihuatanejo" },
  { code: "CZM", city: "Cozumel", country: "MX", name: "Cozumel Intl" },
  { code: "VER", city: "Veracruz", country: "MX", name: "General Heriberto Jara" },
  { code: "TAP", city: "Tapachula", country: "MX", name: "Tapachula Intl" },
  { code: "AGU", city: "Aguascalientes", country: "MX", name: "Lic. Jesús Terán Peredo" },
  { code: "BJX", city: "Leon", country: "MX", name: "Del Bajío Intl" },
  { code: "DGO", city: "Durango", country: "MX", name: "Guadalupe Victoria" },
  { code: "LAP", city: "La Paz", country: "MX", name: "Manuel Márquez de León" },
  { code: "MXL", city: "Mexicali", country: "MX", name: "Mexicali Intl" },
  { code: "HMO", city: "Hermosillo", country: "MX", name: "General Ignacio Pesqueira García" },
  { code: "CUL", city: "Culiacan", country: "MX", name: "Federal de Bachigualato" },
  { code: "TAM", city: "Tampico", country: "MX", name: "Gen. Francisco Javier Mina" },

  // ── Caribbean ──────────────────────────────────────────────────────────────
  { code: "NAS", city: "Nassau", country: "BS", name: "Lynden Pindling Intl" },
  { code: "POS", city: "Port of Spain", country: "TT", name: "Piarco Intl" },
  { code: "BGI", city: "Bridgetown", country: "BB", name: "Grantley Adams Intl" },
  { code: "ANU", city: "Antigua", country: "AG", name: "V.C. Bird Intl" },
  { code: "SXM", city: "St. Maarten", country: "SX", name: "Princess Juliana Intl" },
  { code: "STT", city: "St. Thomas", country: "VI", name: "Cyril E. King" },
  { code: "SJU", city: "San Juan", country: "PR", name: "Luis Muñoz Marín" },
  { code: "GCM", city: "Grand Cayman", country: "KY", name: "Owen Roberts Intl" },
  { code: "KIN", city: "Kingston", country: "JM", name: "Norman Manley Intl" },
  { code: "MBJ", city: "Montego Bay", country: "JM", name: "Sangster Intl" },
  { code: "HAV", city: "Havana", country: "CU", name: "José Martí Intl" },
  { code: "VRA", city: "Varadero", country: "CU", name: "Juan Gualberto Gómez" },
  { code: "SDQ", city: "Santo Domingo", country: "DO", name: "Las Américas Intl" },
  { code: "POP", city: "Puerto Plata", country: "DO", name: "Gregorio Luperón" },
  { code: "PAP", city: "Port-au-Prince", country: "HT", name: "Toussaint Louverture" },
  { code: "GND", city: "Grenada", country: "GD", name: "Maurice Bishop Intl" },
  { code: "SVD", city: "St. Vincent", country: "VC", name: "Argyle Intl" },
  { code: "SLU", city: "St. Lucia", country: "LC", name: "Hewanorra Intl" },
  { code: "SKB", city: "St. Kitts", country: "KN", name: "Robert L. Bradshaw" },
  { code: "TAB", city: "Tobago", country: "TT", name: "A.N.R. Robinson Intl" },
  { code: "BDA", city: "Bermuda", country: "BM", name: "L.F. Wade Intl" },
  { code: "BON", city: "Bonaire", country: "BQ", name: "Flamingo Intl" },
  { code: "CUR", city: "Willemstad", country: "CW", name: "Hato Intl" },
  { code: "AUA", city: "Oranjestad", country: "AW", name: "Queen Beatrix Intl" },

  // ── Central America ────────────────────────────────────────────────────────
  { code: "SJO", city: "San Jose", country: "CR", name: "Juan Santamaría Intl" },
  { code: "LIR", city: "Liberia", country: "CR", name: "Daniel Oduber Quirós" },
  { code: "SAL", city: "San Salvador", country: "SV", name: "Monseñor Óscar Arnulfo Romero" },
  { code: "GUA", city: "Guatemala City", country: "GT", name: "La Aurora Intl" },
  { code: "TGU", city: "Tegucigalpa", country: "HN", name: "Toncontín Intl" },
  { code: "SAP", city: "San Pedro Sula", country: "HN", name: "Ramón Villeda Morales" },
  { code: "MGA", city: "Managua", country: "NI", name: "Augusto C. Sandino" },
  { code: "PTY", city: "Panama City", country: "PA", name: "Tocumen Intl" },
  { code: "BZE", city: "Belize City", country: "BZ", name: "Philip S. W. Goldson Intl" },

  // ── South America ──────────────────────────────────────────────────────────
  { code: "GRU", city: "São Paulo", country: "BR", name: "Guarulhos Intl" },
  { code: "GIG", city: "Rio de Janeiro", country: "BR", name: "Galeão Intl" },
  { code: "BSB", city: "Brasília", country: "BR", name: "Presidente Juscelino Kubitschek" },
  { code: "SSA", city: "Salvador", country: "BR", name: "Deputado Luís Eduardo Magalhães" },
  { code: "FOR", city: "Fortaleza", country: "BR", name: "Pinto Martins Intl" },
  { code: "REC", city: "Recife", country: "BR", name: "Guararapes-Gilberto Freyre" },
  { code: "POA", city: "Porto Alegre", country: "BR", name: "Salgado Filho Intl" },
  { code: "CWB", city: "Curitiba", country: "BR", name: "Afonso Pena Intl" },
  { code: "BEL", city: "Belém", country: "BR", name: "Val de Cans Intl" },
  { code: "MAO", city: "Manaus", country: "BR", name: "Eduardo Gomes Intl" },
  { code: "CGH", city: "São Paulo", country: "BR", name: "Congonhas" },
  { code: "SDU", city: "Rio de Janeiro", country: "BR", name: "Santos Dumont" },
  { code: "FLN", city: "Florianópolis", country: "BR", name: "Hercílio Luz Intl" },
  { code: "NAT", city: "Natal", country: "BR", name: "São Gonçalo do Amarante" },
  { code: "IGU", city: "Foz do Iguaçu", country: "BR", name: "Cataratas Intl" },
  { code: "EZE", city: "Buenos Aires", country: "AR", name: "Ministro Pistarini" },
  { code: "AEP", city: "Buenos Aires", country: "AR", name: "Jorge Newbery" },
  { code: "COR", city: "Córdoba", country: "AR", name: "Ingeniero Ambrosio Taravella" },
  { code: "MDZ", city: "Mendoza", country: "AR", name: "El Plumerillo" },
  { code: "BRC", city: "San Carlos de Bariloche", country: "AR", name: "Bariloche" },
  { code: "USH", city: "Ushuaia", country: "AR", name: "Malvinas Argentinas" },
  { code: "IGR", city: "Puerto Iguazú", country: "AR", name: "Cataratas del Iguazú" },
  { code: "SCL", city: "Santiago", country: "CL", name: "Arturo Merino Benítez" },
  { code: "PMC", city: "Puerto Montt", country: "CL", name: "El Tepual" },
  { code: "IQQ", city: "Iquique", country: "CL", name: "Diego Aracena" },
  { code: "ANF", city: "Antofagasta", country: "CL", name: "Cerro Moreno" },
  { code: "BOG", city: "Bogotá", country: "CO", name: "El Dorado Intl" },
  { code: "MDE", city: "Medellín", country: "CO", name: "José María Córdova" },
  { code: "CLO", city: "Cali", country: "CO", name: "Alfonso Bonilla Aragón" },
  { code: "CTG", city: "Cartagena", country: "CO", name: "Rafael Núñez Intl" },
  { code: "BAQ", city: "Barranquilla", country: "CO", name: "Ernesto Cortissoz" },
  { code: "ADZ", city: "San Andrés", country: "CO", name: "Gustavo Rojas Pinilla" },
  { code: "LIM", city: "Lima", country: "PE", name: "Jorge Chávez Intl" },
  { code: "CUZ", city: "Cusco", country: "PE", name: "Alejandro Velasco Astete" },
  { code: "AQP", city: "Arequipa", country: "PE", name: "Alfredo Rodríguez Ballón" },
  { code: "TRU", city: "Trujillo", country: "PE", name: "Carlos Martínez de Pinillos" },
  { code: "IQT", city: "Iquitos", country: "PE", name: "Coronel Francisco Secada" },
  { code: "GYE", city: "Guayaquil", country: "EC", name: "José Joaquín de Olmedo" },
  { code: "UIO", city: "Quito", country: "EC", name: "Mariscal Sucre Intl" },
  { code: "GPS", city: "Galapagos", country: "EC", name: "Seymour Airport" },
  { code: "CCS", city: "Caracas", country: "VE", name: "Simón Bolívar Intl" },
  { code: "CBB", city: "Cochabamba", country: "BO", name: "Jorge Wilstermann" },
  { code: "LPB", city: "La Paz", country: "BO", name: "El Alto Intl" },
  { code: "VVI", city: "Santa Cruz", country: "BO", name: "Viru Viru Intl" },
  { code: "MVD", city: "Montevideo", country: "UY", name: "Carrasco Intl" },
  { code: "PDP", city: "Punta del Este", country: "UY", name: "Capitán de Corbeta Carlos A. Curbelo" },
  { code: "ASU", city: "Asunción", country: "PY", name: "Silvio Pettirossi Intl" },
  { code: "GEO", city: "Georgetown", country: "GY", name: "Cheddi Jagan Intl" },
  { code: "PBM", city: "Paramaribo", country: "SR", name: "Johan Adolf Pengel" },

  // ── UK & Ireland ───────────────────────────────────────────────────────────
  { code: "LHR", city: "London", country: "GB", name: "Heathrow" },
  { code: "LGW", city: "London", country: "GB", name: "Gatwick" },
  { code: "MAN", city: "Manchester", country: "GB", name: "Manchester Airport" },
  { code: "STN", city: "London", country: "GB", name: "Stansted" },
  { code: "LTN", city: "London", country: "GB", name: "Luton" },
  { code: "EDI", city: "Edinburgh", country: "GB", name: "Edinburgh Airport" },
  { code: "BHX", city: "Birmingham", country: "GB", name: "Birmingham Airport" },
  { code: "GLA", city: "Glasgow", country: "GB", name: "Glasgow Airport" },
  { code: "BRS", city: "Bristol", country: "GB", name: "Bristol Airport" },
  { code: "LPL", city: "Liverpool", country: "GB", name: "John Lennon" },
  { code: "NCL", city: "Newcastle", country: "GB", name: "Newcastle Airport" },
  { code: "ABZ", city: "Aberdeen", country: "GB", name: "Aberdeen Airport" },
  { code: "BFS", city: "Belfast", country: "GB", name: "Belfast Intl" },
  { code: "BHD", city: "Belfast", country: "GB", name: "George Best City" },
  { code: "CWL", city: "Cardiff", country: "GB", name: "Cardiff Airport" },
  { code: "EXT", city: "Exeter", country: "GB", name: "Exeter Airport" },
  { code: "LBA", city: "Leeds", country: "GB", name: "Leeds Bradford" },
  { code: "DUB", city: "Dublin", country: "IE", name: "Dublin Airport" },
  { code: "ORK", city: "Cork", country: "IE", name: "Cork Airport" },
  { code: "SNN", city: "Shannon", country: "IE", name: "Shannon Airport" },
  { code: "NOC", city: "Knock", country: "IE", name: "Ireland West Knock" },
  { code: "JER", city: "Jersey", country: "JE", name: "Jersey Airport" },
  { code: "GCI", city: "Guernsey", country: "GG", name: "Guernsey Airport" },

  // ── Western Europe ─────────────────────────────────────────────────────────
  { code: "CDG", city: "Paris", country: "FR", name: "Charles de Gaulle" },
  { code: "ORY", city: "Paris", country: "FR", name: "Orly" },
  { code: "NCE", city: "Nice", country: "FR", name: "Côte d'Azur" },
  { code: "MRS", city: "Marseille", country: "FR", name: "Provence" },
  { code: "LYS", city: "Lyon", country: "FR", name: "Saint-Exupéry" },
  { code: "TLS", city: "Toulouse", country: "FR", name: "Toulouse-Blagnac" },
  { code: "BOD", city: "Bordeaux", country: "FR", name: "Bordeaux-Mérignac" },
  { code: "NTE", city: "Nantes", country: "FR", name: "Nantes Atlantique" },
  { code: "BIQ", city: "Biarritz", country: "FR", name: "Biarritz Pays Basque" },
  { code: "RNS", city: "Rennes", country: "FR", name: "Rennes-Saint-Jacques" },
  { code: "AMS", city: "Amsterdam", country: "NL", name: "Schiphol" },
  { code: "EIN", city: "Eindhoven", country: "NL", name: "Eindhoven Airport" },
  { code: "RTM", city: "Rotterdam", country: "NL", name: "Rotterdam The Hague" },
  { code: "BRU", city: "Brussels", country: "BE", name: "Brussels Airport" },
  { code: "LGG", city: "Liège", country: "BE", name: "Liège Airport" },
  { code: "CRL", city: "Charleroi", country: "BE", name: "Brussels South Charleroi" },
  { code: "LUX", city: "Luxembourg", country: "LU", name: "Luxembourg Airport" },
  { code: "FRA", city: "Frankfurt", country: "DE", name: "Frankfurt Airport" },
  { code: "MUC", city: "Munich", country: "DE", name: "Munich Airport" },
  { code: "DUS", city: "Dusseldorf", country: "DE", name: "Dusseldorf Airport" },
  { code: "BER", city: "Berlin", country: "DE", name: "Brandenburg Airport" },
  { code: "HAM", city: "Hamburg", country: "DE", name: "Hamburg Airport" },
  { code: "STR", city: "Stuttgart", country: "DE", name: "Stuttgart Airport" },
  { code: "CGN", city: "Cologne", country: "DE", name: "Cologne Bonn Airport" },
  { code: "NUE", city: "Nuremberg", country: "DE", name: "Nuremberg Airport" },
  { code: "LEJ", city: "Leipzig", country: "DE", name: "Leipzig/Halle Airport" },
  { code: "HAJ", city: "Hannover", country: "DE", name: "Hannover Airport" },
  { code: "BRE", city: "Bremen", country: "DE", name: "Bremen Airport" },
  { code: "MAD", city: "Madrid", country: "ES", name: "Adolfo Suárez Barajas" },
  { code: "BCN", city: "Barcelona", country: "ES", name: "El Prat" },
  { code: "AGP", city: "Malaga", country: "ES", name: "Costa del Sol" },
  { code: "ALC", city: "Alicante", country: "ES", name: "Alicante-Elche" },
  { code: "VLC", city: "Valencia", country: "ES", name: "Valencia Airport" },
  { code: "SVQ", city: "Seville", country: "ES", name: "San Pablo" },
  { code: "BIO", city: "Bilbao", country: "ES", name: "Bilbao Airport" },
  { code: "PMI", city: "Palma", country: "ES", name: "Palma de Mallorca" },
  { code: "IBZ", city: "Ibiza", country: "ES", name: "Ibiza Airport" },
  { code: "LPA", city: "Gran Canaria", country: "ES", name: "Gran Canaria Airport" },
  { code: "TFS", city: "Tenerife", country: "ES", name: "Tenerife South" },
  { code: "TFN", city: "Tenerife", country: "ES", name: "Tenerife North" },
  { code: "ACE", city: "Lanzarote", country: "ES", name: "Lanzarote Airport" },
  { code: "FUE", city: "Fuerteventura", country: "ES", name: "Fuerteventura Airport" },
  { code: "LIS", city: "Lisbon", country: "PT", name: "Humberto Delgado" },
  { code: "OPO", city: "Porto", country: "PT", name: "Francisco de Sá Carneiro" },
  { code: "FAO", city: "Faro", country: "PT", name: "Faro Airport" },
  { code: "FNC", city: "Madeira", country: "PT", name: "Madeira Airport" },
  { code: "SID", city: "Sal", country: "CV", name: "Amílcar Cabral Intl" },
  { code: "FCO", city: "Rome", country: "IT", name: "Fiumicino" },
  { code: "CIA", city: "Rome", country: "IT", name: "Ciampino" },
  { code: "MXP", city: "Milan", country: "IT", name: "Malpensa" },
  { code: "LIN", city: "Milan", country: "IT", name: "Linate" },
  { code: "BGY", city: "Bergamo", country: "IT", name: "Orio al Serio" },
  { code: "NAP", city: "Naples", country: "IT", name: "Naples Intl" },
  { code: "VCE", city: "Venice", country: "IT", name: "Marco Polo" },
  { code: "TSF", city: "Venice", country: "IT", name: "Treviso" },
  { code: "CTA", city: "Catania", country: "IT", name: "Catania-Fontanarossa" },
  { code: "PMO", city: "Palermo", country: "IT", name: "Falcone-Borsellino" },
  { code: "BLQ", city: "Bologna", country: "IT", name: "Guglielmo Marconi" },
  { code: "PSA", city: "Pisa", country: "IT", name: "Galileo Galilei" },
  { code: "FLR", city: "Florence", country: "IT", name: "Peretola" },
  { code: "TRN", city: "Turin", country: "IT", name: "Caselle" },
  { code: "VRN", city: "Verona", country: "IT", name: "Villafranca" },
  { code: "GOA", city: "Genoa", country: "IT", name: "Cristoforo Colombo" },
  { code: "BRI", city: "Bari", country: "IT", name: "Bari Karol Wojtyla" },
  { code: "CAG", city: "Cagliari", country: "IT", name: "Cagliari-Elmas" },
  { code: "OLB", city: "Olbia", country: "IT", name: "Costa Smeralda" },
  { code: "ATH", city: "Athens", country: "GR", name: "Eleftherios Venizelos" },
  { code: "SKG", city: "Thessaloniki", country: "GR", name: "Macedonia" },
  { code: "HER", city: "Heraklion", country: "GR", name: "Nikos Kazantzakis" },
  { code: "RHO", city: "Rhodes", country: "GR", name: "Diagoras" },
  { code: "KGS", city: "Kos", country: "GR", name: "Hippocrates" },
  { code: "CFU", city: "Corfu", country: "GR", name: "Ioannis Kapodistrias" },
  { code: "ZTH", city: "Zakynthos", country: "GR", name: "Zakynthos Intl" },
  { code: "JMK", city: "Mykonos", country: "GR", name: "Mykonos Airport" },
  { code: "JTR", city: "Santorini", country: "GR", name: "Santorini Airport" },
  { code: "ZRH", city: "Zurich", country: "CH", name: "Zürich Airport" },
  { code: "GVA", city: "Geneva", country: "CH", name: "Geneva Airport" },
  { code: "BSL", city: "Basel", country: "CH", name: "EuroAirport" },
  { code: "BRN", city: "Bern", country: "CH", name: "Bern Airport" },
  { code: "OSL", city: "Oslo", country: "NO", name: "Oslo Gardermoen" },
  { code: "BGO", city: "Bergen", country: "NO", name: "Bergen Airport" },
  { code: "TRD", city: "Trondheim", country: "NO", name: "Trondheim Vaernes" },
  { code: "TOS", city: "Tromsø", country: "NO", name: "Tromsø Langnes" },
  { code: "SVG", city: "Stavanger", country: "NO", name: "Stavanger Sola" },
  { code: "KRS", city: "Kristiansand", country: "NO", name: "Kristiansand Airport" },
  { code: "BOO", city: "Bodø", country: "NO", name: "Bodø Airport" },
  { code: "CPH", city: "Copenhagen", country: "DK", name: "Kastrup" },
  { code: "BLL", city: "Billund", country: "DK", name: "Billund Airport" },
  { code: "AAL", city: "Aalborg", country: "DK", name: "Aalborg Airport" },
  { code: "AAR", city: "Aarhus", country: "DK", name: "Aarhus Airport" },
  { code: "FAE", city: "Faroe Islands", country: "FO", name: "Vágar Airport" },
  { code: "ARN", city: "Stockholm", country: "SE", name: "Arlanda" },
  { code: "GOT", city: "Gothenburg", country: "SE", name: "Landvetter" },
  { code: "MMX", city: "Malmo", country: "SE", name: "Malmö Airport" },
  { code: "LLA", city: "Luleå", country: "SE", name: "Luleå Airport" },
  { code: "UME", city: "Umeå", country: "SE", name: "Umeå Airport" },
  { code: "OSD", city: "Östersund", country: "SE", name: "Åre Östersund Airport" },
  { code: "HEL", city: "Helsinki", country: "FI", name: "Helsinki-Vantaa" },
  { code: "TMP", city: "Tampere", country: "FI", name: "Tampere-Pirkkala" },
  { code: "TKU", city: "Turku", country: "FI", name: "Turku Airport" },
  { code: "OUL", city: "Oulu", country: "FI", name: "Oulu Airport" },
  { code: "RVN", city: "Rovaniemi", country: "FI", name: "Rovaniemi Airport" },
  { code: "TLL", city: "Tallinn", country: "EE", name: "Lennart Meri Tallinn" },
  { code: "RIX", city: "Riga", country: "LV", name: "Riga Intl" },
  { code: "VNO", city: "Vilnius", country: "LT", name: "Vilnius Airport" },
  { code: "WAW", city: "Warsaw", country: "PL", name: "Chopin Airport" },
  { code: "KRK", city: "Krakow", country: "PL", name: "John Paul II Intl" },
  { code: "WRO", city: "Wroclaw", country: "PL", name: "Copernicus Airport" },
  { code: "POZ", city: "Poznan", country: "PL", name: "Ławica Airport" },
  { code: "GDN", city: "Gdansk", country: "PL", name: "Lech Wałęsa Airport" },
  { code: "KTW", city: "Katowice", country: "PL", name: "Katowice Airport" },
  { code: "BUD", city: "Budapest", country: "HU", name: "Ferenc Liszt Intl" },
  { code: "BTS", city: "Bratislava", country: "SK", name: "M. R. Štefánik Airport" },
  { code: "PRG", city: "Prague", country: "CZ", name: "Václav Havel Airport" },
  { code: "BRQ", city: "Brno", country: "CZ", name: "Brno-Tuřany" },
  { code: "VIE", city: "Vienna", country: "AT", name: "Vienna Intl" },
  { code: "GRZ", city: "Graz", country: "AT", name: "Graz Airport" },
  { code: "INN", city: "Innsbruck", country: "AT", name: "Innsbruck Airport" },
  { code: "SZG", city: "Salzburg", country: "AT", name: "Salzburg Airport" },
  { code: "SOF", city: "Sofia", country: "BG", name: "Sofia Airport" },
  { code: "VAR", city: "Varna", country: "BG", name: "Varna Airport" },
  { code: "BOJ", city: "Burgas", country: "BG", name: "Burgas Airport" },
  { code: "OTP", city: "Bucharest", country: "RO", name: "Henri Coandă Intl" },
  { code: "CLJ", city: "Cluj-Napoca", country: "RO", name: "Avram Iancu Intl" },
  { code: "TSR", city: "Timisoara", country: "RO", name: "Traian Vuia Intl" },
  { code: "IAS", city: "Iasi", country: "RO", name: "Iași Intl" },
  { code: "KIV", city: "Chisinau", country: "MD", name: "Chișinău Intl" },
  { code: "BEG", city: "Belgrade", country: "RS", name: "Nikola Tesla Airport" },
  { code: "ZAG", city: "Zagreb", country: "HR", name: "Franjo Tuđman Airport" },
  { code: "SPU", city: "Split", country: "HR", name: "Split Airport" },
  { code: "DBV", city: "Dubrovnik", country: "HR", name: "Dubrovnik Airport" },
  { code: "ZAD", city: "Zadar", country: "HR", name: "Zadar Airport" },
  { code: "SKP", city: "Skopje", country: "MK", name: "Alexander the Great" },
  { code: "TGD", city: "Podgorica", country: "ME", name: "Podgorica Airport" },
  { code: "TIV", city: "Tivat", country: "ME", name: "Tivat Airport" },
  { code: "SVO", city: "Moscow", country: "RU", name: "Sheremetyevo" },
  { code: "DME", city: "Moscow", country: "RU", name: "Domodedovo" },
  { code: "LED", city: "St. Petersburg", country: "RU", name: "Pulkovo" },
  { code: "KZN", city: "Kazan", country: "RU", name: "Kazan Intl" },
  { code: "AER", city: "Sochi", country: "RU", name: "Sochi Intl" },

  // ── Middle East ────────────────────────────────────────────────────────────
  { code: "DXB", city: "Dubai", country: "AE", name: "Dubai Intl" },
  { code: "AUH", city: "Abu Dhabi", country: "AE", name: "Zayed Intl" },
  { code: "SHJ", city: "Sharjah", country: "AE", name: "Sharjah Intl" },
  { code: "DWC", city: "Dubai", country: "AE", name: "Al Maktoum Intl" },
  { code: "DOH", city: "Doha", country: "QA", name: "Hamad Intl" },
  { code: "BAH", city: "Manama", country: "BH", name: "Bahrain Intl" },
  { code: "KWI", city: "Kuwait City", country: "KW", name: "Kuwait Intl" },
  { code: "MCT", city: "Muscat", country: "OM", name: "Muscat Intl" },
  { code: "AMM", city: "Amman", country: "JO", name: "Queen Alia Intl" },
  { code: "AQJ", city: "Aqaba", country: "JO", name: "King Hussein Intl" },
  { code: "BEY", city: "Beirut", country: "LB", name: "Rafic Hariri Intl" },
  { code: "BGW", city: "Baghdad", country: "IQ", name: "Baghdad Intl" },
  { code: "EBL", city: "Erbil", country: "IQ", name: "Erbil Intl" },
  { code: "THR", city: "Tehran", country: "IR", name: "Imam Khomeini Intl" },
  { code: "MHD", city: "Mashhad", country: "IR", name: "Shahid Hashemi Nejad" },
  { code: "RUH", city: "Riyadh", country: "SA", name: "King Khalid Intl" },
  { code: "JED", city: "Jeddah", country: "SA", name: "King Abdulaziz Intl" },
  { code: "DMM", city: "Dammam", country: "SA", name: "King Fahd Intl" },
  { code: "MED", city: "Medina", country: "SA", name: "Prince Mohammad bin Abdulaziz" },
  { code: "TIF", city: "Taif", country: "SA", name: "Ta'if Regional Airport" },
  { code: "YNB", city: "Yanbu", country: "SA", name: "Yanbu Airport" },
  { code: "ADE", city: "Aden", country: "YE", name: "Aden Intl" },

  // ── Africa ─────────────────────────────────────────────────────────────────
  { code: "CAI", city: "Cairo", country: "EG", name: "Cairo Intl" },
  { code: "HRG", city: "Hurghada", country: "EG", name: "Hurghada Intl" },
  { code: "SSH", city: "Sharm el-Sheikh", country: "EG", name: "Sharm el-Sheikh Intl" },
  { code: "LXR", city: "Luxor", country: "EG", name: "Luxor Intl" },
  { code: "ASW", city: "Aswan", country: "EG", name: "Aswan Intl" },
  { code: "CMN", city: "Casablanca", country: "MA", name: "Mohammed V Intl" },
  { code: "RAK", city: "Marrakech", country: "MA", name: "Marrakech Menara" },
  { code: "RBA", city: "Rabat", country: "MA", name: "Rabat-Salé Airport" },
  { code: "TNG", city: "Tangier", country: "MA", name: "Ibn Batouta" },
  { code: "FES", city: "Fes", country: "MA", name: "Fès-Saïss" },
  { code: "ALG", city: "Algiers", country: "DZ", name: "Houari Boumediene" },
  { code: "TUN", city: "Tunis", country: "TN", name: "Tunis-Carthage" },
  { code: "TIP", city: "Tripoli", country: "LY", name: "Mitiga Intl" },
  { code: "KRT", city: "Khartoum", country: "SD", name: "Khartoum Intl" },
  { code: "ADD", city: "Addis Ababa", country: "ET", name: "Bole Intl" },
  { code: "NBO", city: "Nairobi", country: "KE", name: "Jomo Kenyatta Intl" },
  { code: "MBA", city: "Mombasa", country: "KE" },
  { code: "DAR", city: "Dar es Salaam", country: "TZ", name: "Julius Nyerere Intl" },
  { code: "ZNZ", city: "Zanzibar", country: "TZ", name: "Abeid Amani Karume" },
  { code: "KGL", city: "Kigali", country: "RW", name: "Kigali Intl" },
  { code: "EBB", city: "Kampala", country: "UG", name: "Entebbe Intl" },
  { code: "JNB", city: "Johannesburg", country: "ZA", name: "O.R. Tambo Intl" },
  { code: "CPT", city: "Cape Town", country: "ZA", name: "Cape Town Intl" },
  { code: "DUR", city: "Durban", country: "ZA", name: "King Shaka Intl" },
  { code: "PLZ", city: "Port Elizabeth", country: "ZA", name: "Chief Dawid Stuurman" },
  { code: "MQP", city: "Nelspruit", country: "ZA", name: "Kruger Mpumalanga" },
  { code: "NBO", city: "Nairobi", country: "KE", name: "Jomo Kenyatta Intl" },
  { code: "LOS", city: "Lagos", country: "NG", name: "Murtala Muhammed" },
  { code: "ABV", city: "Abuja", country: "NG", name: "Nnamdi Azikiwe Intl" },
  { code: "KAN", city: "Kano", country: "NG", name: "Mallam Aminu Kano" },
  { code: "ACC", city: "Accra", country: "GH", name: "Kotoka Intl" },
  { code: "ABJ", city: "Abidjan", country: "CI", name: "Félix Houphouët-Boigny" },
  { code: "DKR", city: "Dakar", country: "SN", name: "Blaise Diagne Intl" },
  { code: "CMN", city: "Casablanca", country: "MA", name: "Mohammed V Intl" },
  { code: "BKO", city: "Bamako", country: "ML", name: "Senou Intl" },
  { code: "COO", city: "Cotonou", country: "BJ", name: "Cadjehoun Airport" },
  { code: "OUA", city: "Ouagadougou", country: "BF", name: "Ouagadougou Airport" },
  { code: "FNA", city: "Freetown", country: "SL", name: "Lungi Intl" },
  { code: "BJL", city: "Banjul", country: "GM", name: "Banjul Intl" },
  { code: "CKY", city: "Conakry", country: "GN", name: "Conakry Intl" },
  { code: "LFW", city: "Lomé", country: "TG", name: "Gnassingbé Eyadéma" },
  { code: "DLA", city: "Douala", country: "CM", name: "Douala Intl" },
  { code: "NSI", city: "Yaoundé", country: "CM", name: "Nsimalen Intl" },
  { code: "LBV", city: "Libreville", country: "GA", name: "Léon-Mba Intl" },
  { code: "BZV", city: "Brazzaville", country: "CG", name: "Maya-Maya Airport" },
  { code: "FIH", city: "Kinshasa", country: "CD", name: "N'djili Intl" },
  { code: "GBE", city: "Gaborone", country: "BW", name: "Sir Seretse Khama" },
  { code: "WDH", city: "Windhoek", country: "NA", name: "Hosea Kutako Intl" },
  { code: "MRU", city: "Mauritius", country: "MU", name: "Sir Seewoosagur Ramgoolam" },
  { code: "RUN", city: "Réunion", country: "RE", name: "Roland Garros" },
  { code: "HAH", city: "Moroni", country: "KM", name: "Prince Said Ibrahim" },
  { code: "TNR", city: "Antananarivo", country: "MG", name: "Ivato Intl" },
  { code: "MPM", city: "Maputo", country: "MZ", name: "Maputo Intl" },
  { code: "LUN", city: "Lusaka", country: "ZM", name: "Kenneth Kaunda Intl" },
  { code: "HRE", city: "Harare", country: "ZW", name: "Robert Gabriel Mugabe" },
  { code: "VFA", city: "Victoria Falls", country: "ZW", name: "Victoria Falls Intl" },
  { code: "LAD", city: "Luanda", country: "AO", name: "Quatro de Fevereiro" },
  { code: "SSG", city: "Malabo", country: "GQ", name: "Santa Isabel Airport" },
  { code: "NDJ", city: "N'Djamena", country: "TD", name: "Hassan Djamous" },
  { code: "NIM", city: "Niamey", country: "NE", name: "Diori Hamani Intl" },
  { code: "ROB", city: "Monrovia", country: "LR", name: "Roberts Intl" },
  { code: "BIO", city: "Bilbao", country: "ES", name: "Bilbao Airport" },
  { code: "JIB", city: "Djibouti", country: "DJ", name: "Ambouli Intl" },
  { code: "MGQ", city: "Mogadishu", country: "SO", name: "Aden Adde Intl" },
  { code: "ASM", city: "Asmara", country: "ER", name: "Asmara Intl" },

  // ── East Asia ──────────────────────────────────────────────────────────────
  { code: "PEK", city: "Beijing", country: "CN", name: "Capital Intl" },
  { code: "PKX", city: "Beijing", country: "CN", name: "Daxing Intl" },
  { code: "PVG", city: "Shanghai", country: "CN", name: "Pudong Intl" },
  { code: "SHA", city: "Shanghai", country: "CN", name: "Hongqiao" },
  { code: "CAN", city: "Guangzhou", country: "CN", name: "Baiyun Intl" },
  { code: "SZX", city: "Shenzhen", country: "CN", name: "Bao'an Intl" },
  { code: "CTU", city: "Chengdu", country: "CN", name: "Tianfu Intl" },
  { code: "TFU", city: "Chengdu", country: "CN", name: "Shuangliu Intl" },
  { code: "CKG", city: "Chongqing", country: "CN", name: "Jiangbei Intl" },
  { code: "XMN", city: "Xiamen", country: "CN", name: "Gaoqi Intl" },
  { code: "NKG", city: "Nanjing", country: "CN", name: "Lukou Intl" },
  { code: "HGH", city: "Hangzhou", country: "CN", name: "Xiaoshan Intl" },
  { code: "WUH", city: "Wuhan", country: "CN", name: "Tianhe Intl" },
  { code: "TSN", city: "Tianjin", country: "CN", name: "Binhai Intl" },
  { code: "TAO", city: "Qingdao", country: "CN", name: "Jiaodong Intl" },
  { code: "XIY", city: "Xi'an", country: "CN", name: "Xianyang Intl" },
  { code: "KMG", city: "Kunming", country: "CN", name: "Changshui Intl" },
  { code: "CSX", city: "Changsha", country: "CN", name: "Huanghua Intl" },
  { code: "HRB", city: "Harbin", country: "CN", name: "Taiping Intl" },
  { code: "SHE", city: "Shenyang", country: "CN", name: "Taoxian Intl" },
  { code: "DLC", city: "Dalian", country: "CN", name: "Zhoushuizi Intl" },
  { code: "LHW", city: "Lanzhou", country: "CN", name: "Zhongchuan Intl" },
  { code: "NNG", city: "Nanning", country: "CN", name: "Wuxu Intl" },
  { code: "KWL", city: "Guilin", country: "CN", name: "Liangjiang Intl" },
  { code: "HAK", city: "Haikou", country: "CN", name: "Meilan Intl" },
  { code: "SYX", city: "Sanya", country: "CN", name: "Phoenix Intl" },
  { code: "URC", city: "Urumqi", country: "CN", name: "Diwopu Intl" },
  { code: "HKG", city: "Hong Kong", country: "HK", name: "Hong Kong Intl" },
  { code: "MFM", city: "Macau", country: "MO", name: "Macau Intl" },
  { code: "TPE", city: "Taipei", country: "TW", name: "Taiwan Taoyuan Intl" },
  { code: "TSA", city: "Taipei", country: "TW", name: "Songshan" },
  { code: "KHH", city: "Kaohsiung", country: "TW", name: "Kaohsiung Intl" },
  { code: "RMQ", city: "Taichung", country: "TW", name: "Taichung Intl" },
  { code: "ICN", city: "Seoul", country: "KR", name: "Incheon Intl" },
  { code: "GMP", city: "Seoul", country: "KR", name: "Gimpo Intl" },
  { code: "PUS", city: "Busan", country: "KR", name: "Gimhae Intl" },
  { code: "CJU", city: "Jeju", country: "KR", name: "Jeju Intl" },
  { code: "TAE", city: "Daegu", country: "KR", name: "Daegu Intl" },
  { code: "CJJ", city: "Cheongju", country: "KR", name: "Cheongju Intl" },
  { code: "NRT", city: "Tokyo", country: "JP", name: "Narita Intl" },
  { code: "HND", city: "Tokyo", country: "JP", name: "Haneda" },
  { code: "KIX", city: "Osaka", country: "JP", name: "Kansai Intl" },
  { code: "ITM", city: "Osaka", country: "JP", name: "Itami" },
  { code: "NGO", city: "Nagoya", country: "JP", name: "Chubu Centrair" },
  { code: "CTS", city: "Sapporo", country: "JP", name: "New Chitose" },
  { code: "FUK", city: "Fukuoka", country: "JP", name: "Fukuoka Airport" },
  { code: "OKA", city: "Okinawa", country: "JP", name: "Naha Airport" },
  { code: "HIJ", city: "Hiroshima", country: "JP", name: "Hiroshima Airport" },
  { code: "SDJ", city: "Sendai", country: "JP", name: "Sendai Airport" },
  { code: "NGS", city: "Nagasaki", country: "JP", name: "Nagasaki Airport" },
  { code: "KOJ", city: "Kagoshima", country: "JP", name: "Kagoshima Airport" },
  { code: "OIT", city: "Oita", country: "JP", name: "Oita Airport" },
  { code: "KMI", city: "Miyazaki", country: "JP", name: "Miyazaki Airport" },
  { code: "ISG", city: "Ishigaki", country: "JP", name: "New Ishigaki Airport" },
  { code: "MMB", city: "Memanbetsu", country: "JP", name: "Memanbetsu Airport" },
  { code: "AXT", city: "Akita", country: "JP", name: "Akita Airport" },

  // ── Southeast Asia ─────────────────────────────────────────────────────────
  { code: "BKK", city: "Bangkok", country: "TH", name: "Suvarnabhumi" },
  { code: "DMK", city: "Bangkok", country: "TH", name: "Don Mueang" },
  { code: "CNX", city: "Chiang Mai", country: "TH", name: "Chiang Mai Intl" },
  { code: "HKT", city: "Phuket", country: "TH", name: "Phuket Intl" },
  { code: "HDY", city: "Hat Yai", country: "TH", name: "Hat Yai Intl" },
  { code: "KBV", city: "Krabi", country: "TH", name: "Krabi Airport" },
  { code: "USM", city: "Koh Samui", country: "TH", name: "Samui Airport" },
  { code: "SGN", city: "Ho Chi Minh City", country: "VN", name: "Tan Son Nhat" },
  { code: "HAN", city: "Hanoi", country: "VN", name: "Noi Bai Intl" },
  { code: "DAD", city: "Da Nang", country: "VN", name: "Da Nang Intl" },
  { code: "CXR", city: "Nha Trang", country: "VN", name: "Cam Ranh Intl" },
  { code: "PQC", city: "Phu Quoc", country: "VN", name: "Phu Quoc Intl" },
  { code: "VCA", city: "Can Tho", country: "VN", name: "Can Tho Intl" },
  { code: "PNH", city: "Phnom Penh", country: "KH", name: "Phnom Penh Intl" },
  { code: "REP", city: "Siem Reap", country: "KH", name: "Siem Reap-Angkor Intl" },
  { code: "VTE", city: "Vientiane", country: "LA", name: "Wattay Intl" },
  { code: "LPQ", city: "Luang Prabang", country: "LA", name: "Luang Prabang Intl" },
  { code: "RGN", city: "Yangon", country: "MM", name: "Yangon Intl" },
  { code: "MDL", city: "Mandalay", country: "MM", name: "Mandalay Intl" },
  { code: "KUL", city: "Kuala Lumpur", country: "MY", name: "Kuala Lumpur Intl" },
  { code: "SZB", city: "Kuala Lumpur", country: "MY", name: "Sultan Abdul Aziz Shah" },
  { code: "PEN", city: "Penang", country: "MY", name: "Penang Intl" },
  { code: "BKI", city: "Kota Kinabalu", country: "MY", name: "Kota Kinabalu Intl" },
  { code: "KCH", city: "Kuching", country: "MY", name: "Kuching Intl" },
  { code: "LBU", city: "Labuan", country: "MY", name: "Labuan Airport" },
  { code: "MYY", city: "Miri", country: "MY", name: "Miri Airport" },
  { code: "JHB", city: "Johor Bahru", country: "MY", name: "Senai Intl" },
  { code: "SIN", city: "Singapore", country: "SG", name: "Changi Airport" },
  { code: "MNL", city: "Manila", country: "PH", name: "Ninoy Aquino Intl" },
  { code: "CEB", city: "Cebu", country: "PH", name: "Mactan-Cebu Intl" },
  { code: "DVO", city: "Davao", country: "PH", name: "Francisco Bangoy Intl" },
  { code: "ILO", city: "Iloilo", country: "PH", name: "Iloilo Intl" },
  { code: "PPS", city: "Puerto Princesa", country: "PH", name: "Puerto Princesa Intl" },
  { code: "ZAM", city: "Zamboanga", country: "PH", name: "Zamboanga Intl" },
  { code: "CGK", city: "Jakarta", country: "ID", name: "Soekarno-Hatta" },
  { code: "HLP", city: "Jakarta", country: "ID", name: "Halim Perdanakusuma" },
  { code: "SUB", city: "Surabaya", country: "ID", name: "Juanda Intl" },
  { code: "DPS", city: "Bali", country: "ID", name: "Ngurah Rai Intl" },
  { code: "UPG", city: "Makassar", country: "ID", name: "Sultan Hasanuddin" },
  { code: "BPN", city: "Balikpapan", country: "ID", name: "Sultan Aji Muhammad Sulaiman" },
  { code: "MDC", city: "Manado", country: "ID", name: "Sam Ratulangi" },
  { code: "JOG", city: "Yogyakarta", country: "ID", name: "Adisutjipto Intl" },
  { code: "LOP", city: "Lombok", country: "ID", name: "Lombok Intl" },
  { code: "SOC", city: "Solo", country: "ID", name: "Adisumarmo Intl" },
  { code: "PDG", city: "Padang", country: "ID", name: "Minangkabau Intl" },
  { code: "PLM", city: "Palembang", country: "ID", name: "Sultan Mahmud Badaruddin II" },
  { code: "PKU", city: "Pekanbaru", country: "ID", name: "Sultan Syarif Kasim II" },
  { code: "SRG", city: "Semarang", country: "ID", name: "Ahmad Yani Intl" },
  { code: "AMQ", city: "Ambon", country: "ID", name: "Pattimura Intl" },
  { code: "TKG", city: "Bandar Lampung", country: "ID", name: "Radin Inten II" },

  // ── South Asia ─────────────────────────────────────────────────────────────
  { code: "DEL", city: "Delhi", country: "IN", name: "Indira Gandhi Intl" },
  { code: "BOM", city: "Mumbai", country: "IN", name: "Chhatrapati Shivaji Maharaj" },
  { code: "MAA", city: "Chennai", country: "IN", name: "Chennai Intl" },
  { code: "CCU", city: "Kolkata", country: "IN", name: "Netaji Subhas Chandra Bose" },
  { code: "BLR", city: "Bangalore", country: "IN", name: "Kempegowda Intl" },
  { code: "HYD", city: "Hyderabad", country: "IN", name: "Rajiv Gandhi Intl" },
  { code: "COK", city: "Kochi", country: "IN", name: "Cochin Intl" },
  { code: "AMD", city: "Ahmedabad", country: "IN", name: "Sardar Vallabhbhai Patel" },
  { code: "PNQ", city: "Pune", country: "IN", name: "Pune Airport" },
  { code: "GOI", city: "Goa", country: "IN", name: "Goa Intl" },
  { code: "TRV", city: "Thiruvananthapuram", country: "IN", name: "Trivandrum Intl" },
  { code: "IXB", city: "Bagdogra", country: "IN", name: "Bagdogra Airport" },
  { code: "IXM", city: "Madurai", country: "IN", name: "Madurai Airport" },
  { code: "PAT", city: "Patna", country: "IN", name: "Jay Prakash Narayan" },
  { code: "BBI", city: "Bhubaneswar", country: "IN", name: "Biju Patnaik Intl" },
  { code: "LKO", city: "Lucknow", country: "IN", name: "Chaudhary Charan Singh" },
  { code: "JAI", city: "Jaipur", country: "IN", name: "Jaipur Intl" },
  { code: "ATQ", city: "Amritsar", country: "IN", name: "Sri Guru Ram Dass Jee" },
  { code: "SXR", city: "Srinagar", country: "IN", name: "Sheikh ul Alam Intl" },
  { code: "VNS", city: "Varanasi", country: "IN", name: "Lal Bahadur Shastri" },
  { code: "GAU", city: "Guwahati", country: "IN", name: "Lokpriya Gopinath Bordoloi" },
  { code: "DAC", city: "Dhaka", country: "BD", name: "Hazrat Shahjalal Intl" },
  { code: "CGP", city: "Chittagong", country: "BD", name: "Shah Amanat Intl" },
  { code: "CMB", city: "Colombo", country: "LK", name: "Bandaranaike Intl" },
  { code: "KTM", city: "Kathmandu", country: "NP", name: "Tribhuvan Intl" },
  { code: "PKR", city: "Pokhara", country: "NP", name: "Pokhara Regional" },
  { code: "BWA", city: "Bhairahawa", country: "NP", name: "Gautam Buddha Intl" },
  { code: "ISB", city: "Islamabad", country: "PK", name: "New Islamabad Intl" },
  { code: "LHE", city: "Lahore", country: "PK", name: "Allama Iqbal Intl" },
  { code: "KHI", city: "Karachi", country: "PK", name: "Jinnah Intl" },
  { code: "PEW", city: "Peshawar", country: "PK", name: "Bacha Khan Intl" },
  { code: "TIA", city: "Tirana", country: "AL", name: "Mother Teresa Intl" },
  { code: "KBL", city: "Kabul", country: "AF", name: "Hamid Karzai Intl" },
  { code: "HEA", city: "Herat", country: "AF", name: "Herat Airport" },
  { code: "MZR", city: "Mazar-e-Sharif", country: "AF", name: "Mazar-e-Sharif Intl" },

  // ── Central Asia ───────────────────────────────────────────────────────────
  { code: "ALA", city: "Almaty", country: "KZ", name: "Almaty Intl" },
  { code: "TSE", city: "Astana", country: "KZ", name: "Nursultan Nazarbayev" },
  { code: "FRU", city: "Bishkek", country: "KG", name: "Manas Intl" },
  { code: "TAS", city: "Tashkent", country: "UZ", name: "Islam Karimov Intl" },
  { code: "SKD", city: "Samarkand", country: "UZ", name: "Samarkand Intl" },
  { code: "ASB", city: "Ashgabat", country: "TM", name: "Ashgabat Intl" },
  { code: "DYU", city: "Dushanbe", country: "TJ", name: "Dushanbe Intl" },
  { code: "GYD", city: "Baku", country: "AZ", name: "Heydar Aliyev Intl" },
  { code: "EVN", city: "Yerevan", country: "AM", name: "Zvartnots Intl" },
  { code: "TBS", city: "Tbilisi", country: "GE", name: "Shota Rustaveli" },
  { code: "BUS", city: "Batumi", country: "GE", name: "Batumi Intl" },

  // ── Oceania ────────────────────────────────────────────────────────────────
  { code: "SYD", city: "Sydney", country: "AU", name: "Kingsford Smith" },
  { code: "MEL", city: "Melbourne", country: "AU", name: "Tullamarine" },
  { code: "BNE", city: "Brisbane", country: "AU", name: "Brisbane Airport" },
  { code: "PER", city: "Perth", country: "AU", name: "Perth Airport" },
  { code: "ADL", city: "Adelaide", country: "AU", name: "Adelaide Airport" },
  { code: "OOL", city: "Gold Coast", country: "AU", name: "Gold Coast Airport" },
  { code: "CNS", city: "Cairns", country: "AU", name: "Cairns Airport" },
  { code: "CBR", city: "Canberra", country: "AU", name: "Canberra Airport" },
  { code: "HBA", city: "Hobart", country: "AU", name: "Hobart Airport" },
  { code: "TSV", city: "Townsville", country: "AU", name: "Townsville Airport" },
  { code: "DRW", city: "Darwin", country: "AU", name: "Darwin Intl" },
  { code: "MKY", city: "Mackay", country: "AU", name: "Mackay Airport" },
  { code: "ROK", city: "Rockhampton", country: "AU", name: "Rockhampton Airport" },
  { code: "LST", city: "Launceston", country: "AU", name: "Launceston Airport" },
  { code: "AKL", city: "Auckland", country: "NZ", name: "Auckland Airport" },
  { code: "CHC", city: "Christchurch", country: "NZ", name: "Christchurch Airport" },
  { code: "WLG", city: "Wellington", country: "NZ", name: "Wellington Airport" },
  { code: "ZQN", city: "Queenstown", country: "NZ", name: "Queenstown Airport" },
  { code: "DUD", city: "Dunedin", country: "NZ", name: "Dunedin Airport" },
  { code: "NSN", city: "Nelson", country: "NZ", name: "Nelson Airport" },
  { code: "HLZ", city: "Hamilton", country: "NZ", name: "Hamilton Airport" },
  { code: "ROT", city: "Rotorua", country: "NZ", name: "Rotorua Airport" },
  { code: "NPE", city: "Napier", country: "NZ", name: "Hawke's Bay Airport" },
  { code: "PPT", city: "Papeete", country: "PF", name: "Faa'a Intl" },
  { code: "BOB", city: "Bora Bora", country: "PF", name: "Motu Mute Airport" },
  { code: "MOZ", city: "Moorea", country: "PF", name: "Moorea Airport" },
  { code: "APW", city: "Apia", country: "WS", name: "Faleolo Intl" },
  { code: "NAN", city: "Nadi", country: "FJ", name: "Nadi Intl" },
  { code: "SUV", city: "Suva", country: "FJ", name: "Nausori Intl" },
  { code: "TBU", city: "Nuku'alofa", country: "TO", name: "Fua'amotu Intl" },
  { code: "HIR", city: "Honiara", country: "SB", name: "Henderson Intl" },
  { code: "POM", city: "Port Moresby", country: "PG", name: "Jacksons Intl" },
  { code: "WWK", city: "Wewak", country: "PG", name: "Wewak Airport" },
  { code: "LAE", city: "Lae", country: "PG", name: "Nadzab Airport" },
  { code: "RAB", city: "Rabaul", country: "PG", name: "Tokua Airport" },
];

// Search function — matches by code, city, or country (case-insensitive)
export function searchAirports(query: string, limit = 6): Airport[] {
  if (!query || query.length < 1) return [];
  const q = query.toUpperCase().trim();
  const results: Airport[] = [];
  // Exact code match first
  for (const a of AIRPORTS) {
    if (a.code === q) { results.push(a); }
  }
  // Code starts-with
  for (const a of AIRPORTS) {
    if (a.code !== q && a.code.startsWith(q) && results.length < limit) { results.push(a); }
  }
  // City starts-with
  for (const a of AIRPORTS) {
    if (!results.includes(a) && a.city.toUpperCase().startsWith(q) && results.length < limit) { results.push(a); }
  }
  // City contains
  for (const a of AIRPORTS) {
    if (!results.includes(a) && a.city.toUpperCase().includes(q) && results.length < limit) { results.push(a); }
  }
  // Name contains
  for (const a of AIRPORTS) {
    if (!results.includes(a) && a.name?.toUpperCase().includes(q) && results.length < limit) { results.push(a); }
  }
  return results.slice(0, limit);
}