"""
build_airports.py
-----------------
Run from RewardWise_MVP0/Backend/:
    python scripts/build_airports.py --csv path/to/airports.csv

Outputs:
    app/validators/airport_codes.py
    app/data/airport_metadata.json
    ../Frontend/components/airports.ts
    ../Frontend/data/airportCoordinates.ts
"""

import argparse
import csv
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

EXCLUDE_TYPES = {"heliport", "balloonport", "closed"}

CONTINENT_NAMES = {
    "AF": "Africa", "AN": "Antarctica", "AS": "Asia",
    "EU": "Europe", "NA": "North America", "OC": "Oceania", "SA": "South America",
}


def clean(value: str) -> str:
    return re.sub(r"\s+", " ", (value or "").strip())


def normal_alias(value: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[^\w\s]", " ", value.lower())).strip()


def unique_aliases(values: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for v in values:
        a = normal_alias(v)
        if a and a not in seen:
            seen.add(a)
            out.append(a)
    return out


def safe_float(value: str):
    try:
        return float(value) if value and value.strip() else None
    except ValueError:
        return None


def build_aliases(row: dict, iata: str, country: str, region: str) -> list[str]:
    city = clean(row.get("municipality", ""))
    name = clean(row.get("name", ""))
    ident = clean(row.get("ident", ""))
    gps = clean(row.get("gps_code", ""))
    local = clean(row.get("local_code", ""))
    icao = clean(row.get("icao_code", ""))
    keywords = [k.strip() for k in re.split(r"[,;/|]", row.get("keywords", "") or "") if k.strip()]

    candidates = [
        iata, name, city,
        f"{city} airport" if city else "",
        f"{city} {iata}" if city else "",
        f"{city} {name}" if city and name and city.lower() not in name.lower() else "",
        ident, gps, local, icao, region,
        f"{city} {region}" if city and region else "",
        f"{city} {country}" if city and country else "",
        *keywords,
    ]
    return unique_aliases(candidates)


def load_airports(csv_path: Path) -> list[dict]:
    with csv_path.open(encoding="utf-8") as f:
        return list(csv.DictReader(f))


def filter_airports(rows: list[dict]) -> list[dict]:
    seen: dict[str, dict] = {}
    type_rank = {"large_airport": 0, "medium_airport": 1, "small_airport": 2}

    for row in rows:
        iata = clean(row.get("iata_code", "")).upper()
        if not iata:
            continue
        if clean(row.get("scheduled_service", "")).lower() != "yes":
            continue
        if clean(row.get("type", "")).lower() in EXCLUDE_TYPES:
            continue
        if iata not in seen:
            seen[iata] = row
        else:
            existing_rank = type_rank.get(clean(seen[iata].get("type", "")).lower(), 9)
            new_rank = type_rank.get(clean(row.get("type", "")).lower(), 9)
            if new_rank < existing_rank:
                seen[iata] = row

    return sorted(seen.values(), key=lambda r: clean(r.get("iata_code", "")).upper())


def build_metadata_row(row: dict) -> dict:
    iata = clean(row.get("iata_code", "")).upper()
    continent_code = clean(row.get("continent", "")).upper()
    country_code = clean(row.get("iso_country", "")).upper()
    region_code = clean(row.get("iso_region", "")).upper()

    return {
        "iata": iata,
        "name": clean(row.get("name", "")) or f"{iata} Airport",
        "city": clean(row.get("municipality", "")),
        "region": region_code,
        "region_code": region_code,
        "country": country_code,
        "country_code": country_code,
        "continent": CONTINENT_NAMES.get(continent_code, continent_code),
        "continent_code": continent_code,
        "latitude": safe_float(row.get("latitude_deg", "")),
        "longitude": safe_float(row.get("longitude_deg", "")),
        "airport_type": clean(row.get("type", "")),
        "scheduled_service": True,
        "ident": clean(row.get("ident", "")),
        "gps_code": clean(row.get("gps_code", "")),
        "local_code": clean(row.get("local_code", "")),
        "aliases": build_aliases(row, iata, country_code, region_code),
        "metadata_quality": "ourairports",
    }


def write_airport_codes(airports: list[dict], out_path: Path) -> None:
    codes = sorted(m["iata"] for m in airports)
    lines = []
    for i in range(0, len(codes), 10):
        chunk = codes[i:i+10]
        lines.append("    " + ", ".join(f'"{c}"' for c in chunk) + ",")

    content = f'''\
# airport_codes.py
# Auto-generated by scripts/build_airports.py — do not edit manually.
# Source: OurAirports airports.csv (scheduled_service=yes, IATA code present,
#         type not in heliport/balloonport/closed)
# Total codes: {len(codes)}

VALID_AIRPORT_CODES = {{
{chr(10).join(lines)}
}}


def is_valid_airport_code(code: str) -> bool:
    """Returns True if the given string is a known IATA airport code."""
    if not code or not isinstance(code, str):
        return False
    return code.upper().strip() in VALID_AIRPORT_CODES


def normalize_airport_code(code: str) -> str:
    """Normalizes an airport code to uppercase. Raises ValueError if invalid."""
    normalized = code.upper().strip()
    if normalized not in VALID_AIRPORT_CODES:
        raise ValueError(f"\'{{code}}\' is not a recognized IATA airport code.")
    return normalized
'''
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"  Wrote {out_path}  ({len(codes)} codes)")


def write_metadata_json(airports: list[dict], out_path: Path) -> None:
    payload = {
        "schema_version": "2.1",
        "source": "OurAirports",
        "source_url": "https://davidmegginson.github.io/ourairports-data/airports.csv",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "airport_count": len(airports),
        "airports": airports,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"  Wrote {out_path}  ({len(airports)} airports)")


def escape_ts(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'")


def write_airports_ts(airports: list[dict], out_path: Path) -> None:
    lines = []
    for a in airports:
        code = escape_ts(a["iata"])
        city = escape_ts(a["city"] or a["iata"])
        country = escape_ts(a["country_code"])
        name = escape_ts(a["name"])
        lines.append(f'  {{ code: "{code}", city: "{city}", country: "{country}", name: "{name}" }},')

    content = f'''\
// airports.ts
// Auto-generated by scripts/build_airports.py — do not edit manually.
// Source: OurAirports airports.csv
// Total airports: {len(airports)}

export interface Airport {{
  code: string;
  city: string;
  country: string;
  name?: string;
}}

export const AIRPORTS: Airport[] = [
{chr(10).join(lines)}
];

// Search function — matches by code, city, name, or country (case-insensitive)
export function searchAirports(query: string, limit = 6): Airport[] {{
  if (!query || query.length < 1) return [];
  const q = query.toUpperCase().trim();
  const results: Airport[] = [];
  // Exact code match first
  for (const a of AIRPORTS) {{
    if (a.code === q) {{ results.push(a); }}
  }}
  // Code starts-with
  for (const a of AIRPORTS) {{
    if (a.code !== q && a.code.startsWith(q) && results.length < limit) {{ results.push(a); }}
  }}
  // City starts-with
  for (const a of AIRPORTS) {{
    if (!results.includes(a) && a.city.toUpperCase().startsWith(q) && results.length < limit) {{ results.push(a); }}
  }}
  // City contains
  for (const a of AIRPORTS) {{
    if (!results.includes(a) && a.city.toUpperCase().includes(q) && results.length < limit) {{ results.push(a); }}
  }}
  // Name contains
  for (const a of AIRPORTS) {{
    if (!results.includes(a) && a.name?.toUpperCase().includes(q) && results.length < limit) {{ results.push(a); }}
  }}
  return results.slice(0, limit);
}}
'''
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"  Wrote {out_path}  ({len(airports)} airports)")


def write_airport_coordinates_ts(airports: list[dict], out_path: Path) -> None:
    lines = []
    for a in airports:
        if a.get("latitude") is None or a.get("longitude") is None:
            continue

        code = escape_ts(a["iata"])
        name = escape_ts(a["name"])
        city = escape_ts(a["city"])
        country = escape_ts(a["country_code"])
        country_code = escape_ts(a["country_code"])
        continent = escape_ts(a.get("continent", ""))
        continent_code = escape_ts(a.get("continent_code", ""))
        latitude = a["latitude"]
        longitude = a["longitude"]

        lines.append(
            '  "' + code + '": {\\n'
            '    iata: "' + code + '",\\n'
            '    name: "' + name + '",\\n'
            '    city: "' + city + '",\\n'
            '    country: "' + country + '",\\n'
            '    countryCode: "' + country_code + '",\\n'
            '    continent: "' + continent + '",\\n'
            '    continentCode: "' + continent_code + '",\\n'
            '    latitude: ' + str(latitude) + ',\\n'
            '    longitude: ' + str(longitude) + ',\\n'
            '  },'
        )

    content = (
        '/** @format */\\n\\n'
        '// Auto-generated from Backend/app/data/airport_metadata.json.\\n'
        '// Do not edit manually; run Backend/scripts/build_airports.py after updating airport data.\\n\\n'
        'export type AirportCoordinate = {\\n'
        '  iata: string;\\n'
        '  name: string;\\n'
        '  city: string;\\n'
        '  country: string;\\n'
        '  countryCode: string;\\n'
        '  continent: string;\\n'
        '  continentCode: string;\\n'
        '  latitude: number;\\n'
        '  longitude: number;\\n'
        '};\\n\\n'
        'export const AIRPORT_COORDINATES: Record<string, AirportCoordinate> = {\\n'
        + chr(10).join(lines)
        + '\\n} as const;\\n\\n'
        'export function getAirportCoordinate(iata?: string | null): AirportCoordinate | undefined {\\n'
        '  if (!iata) return undefined;\\n'
        '  return AIRPORT_COORDINATES[iata.trim().toUpperCase()];\\n'
        '}\\n'
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"  Wrote {out_path}  ({len(lines)} airport coordinates)")


def main():
    parser = argparse.ArgumentParser(description="Build airport files from OurAirports CSV.")
    parser.add_argument("--csv", required=True, help="Path to OurAirports airports.csv")
    parser.add_argument("--backend-root", default=".", help="Path to the Backend/ directory")
    args = parser.parse_args()

    csv_path = Path(args.csv).resolve()
    backend_root = Path(args.backend_root).resolve()
    frontend_root = backend_root.parent / "Frontend"

    codes_out   = backend_root  / "app" / "validators" / "airport_codes.py"
    json_out    = backend_root  / "app" / "data" / "airport_metadata.json"
    ts_out      = frontend_root / "components" / "airports.ts"
    coords_out  = frontend_root / "data" / "airportCoordinates.ts"

    if not csv_path.exists():
        print(f"ERROR: CSV not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading {csv_path} ...")
    rows = load_airports(csv_path)
    print(f"  Total rows: {len(rows)}")

    filtered = filter_airports(rows)
    print(f"  After filter: {len(filtered)}")

    airports = [build_metadata_row(r) for r in filtered]

    print("Writing outputs...")
    write_airport_codes(airports, codes_out)
    write_metadata_json(airports, json_out)
    write_airports_ts(airports, ts_out)
    write_airport_coordinates_ts(airports, coords_out)

    print("Done.")


if __name__ == "__main__":
    main()