# airport_codes.py
# Comprehensive set of active IATA airport codes for input validation.
# Source: IATA airport code registry (commercial airports worldwide).
# Place this file at: RewardWise_MVP0/Backend/app/validators/airport_codes.py

VALID_AIRPORT_CODES = {
    # United States
    "ATL", "LAX", "ORD", "DFW", "DEN", "JFK", "SFO", "SEA", "LAS", "MCO",
    "EWR", "CLT", "PHX", "IAH", "MIA", "BOS", "MSP", "FLL", "DTW", "PHL",
    "LGA", "BWI", "SLC", "DCA", "SAN", "MDW", "TPA", "PDX", "HNL", "DAL",
    "STL", "BNA", "OAK", "AUS", "MCI", "RDU", "SJC", "SMF", "IAD", "MSY",
    "SNA", "RSW", "MKE", "PIT", "CMH", "SAT", "IND", "ABQ", "BDL", "BUF",
    "OMA", "TUL", "OKC", "CVG", "PBI", "JAX", "CLE", "MEM", "RIC", "ONT",
    "SJU", "ANC", "BOI", "GEG", "SDF", "ORF", "GSP", "ROC", "SYR", "ALB",
    "BHM", "TUS", "ELP", "LIT", "ICT", "XNA", "PNS", "MOB", "GPT", "HSV",
    "DSM", "GRR", "FSD", "MSN", "MHT", "PVD", "PWM", "BTV", "ORH", "BGR",
    "FAI", "JNU", "KTN", "SIT", "YAK", "CDV", "OME", "BET", "ADQ", "AKN",
    "HPN", "ISP", "SWF", "ACY", "TTN", "ABE", "AVP", "IPT", "ERI", "AGC",
    "MDT", "CRW", "HTS", "CKB", "EKO", "RNO", "LIH", "OGG", "KOA", "ITO",
    "MFR", "EUG", "RDM", "AST", "SBA", "SBP", "SMX", "BFL", "FAT", "VIS",
    "MOD", "SCK", "MRY", "STS", "ACV", "CEC", "CIC", "RDD", "IPL", "YUM",
    "TYS", "CHA", "TRI", "AVL", "ILM", "CAE", "GSO", "FAY", "OAJ", "EWN",
    "HDN", "GJT", "PUB", "COS", "GUC", "DRO", "MTJ", "ASE", "FNL", "RAP",
    "BIS", "FAR", "MOT", "GFK", "ISN", "DVL", "ATW", "CWA", "LSE", "DLH",
    "HIB", "INL", "BRD", "RST", "AEL", "STC", "EAU", "LAN", "FNT", "MBS",
    "APN", "ESC", "MQT", "PLN", "TVC", "ALO", "CID", "DBQ", "SUX", "BRL",
    "FOD", "MCW", "SPW", "LBF", "GRI", "LNK", "OFK", "ANB", "CSG", "ABY",
    "VLD", "SAV", "AGS", "MCN", "MLU", "SHV", "AEX", "LCH", "BTR", "LFT",
    "HOU", "GGG", "TYR", "ABI", "SJT", "MAF", "LBB", "AMA", "LRD", "HRL",
    "BRO", "CRP", "VCT", "DRT", "MFE", "GRK", "ACT", "SPS", "LAW", "TXK",
    "FSM", "FYV", "JLN", "SGF", "COU", "JEF", "TBN", "UIN", "SUS", "CPS",
    "HKY", "INT", "EGE", "HAP", "PIH", "TWF", "SUN", "LWS", "MYL", "SMN",
    "BZN", "HLN", "GTF", "GGW", "HVR", "MLS", "BIL", "CPR", "RKS", "CYS",
    "JAC", "COD", "WRL", "GCC", "SHR", "LAR", "RIW", "EVW", "MPV", "BTV",
    "LEB", "MHT", "CON", "PSM", "ACK", "MVY", "HYA", "EEN", "FIT", "FOK",
    "OXC", "BDR", "HVN", "GON", "OWD", "CEF", "LYH", "CHO", "SHD", "NTD",
    "DAB", "MLB", "PIE", "SRQ", "PGD", "EYW", "CEW", "VPS", "NAS", "GNV",
    "OCF", "LAL", "APF", "BCT", "PMP", "PHF", "LYH", "HHH", "MYR", "CRE",
    "GYH", "AND", "GMU", "HKY", "SOP", "ETC", "FLO", "CHS", "MHH", "ELH",
    "GHB", "TCB", "AXM", "ZSA", "ASD", "COX", "CRI", "BIM", "RSD", "TBI",
    "MYG", "PPO", "WKR", "LGI", "MAY", "DCT", "IGA", "CEI", "GGT",

    # Canada
    "YYZ", "YVR", "YUL", "YYC", "YEG", "YOW", "YHZ", "YWG", "YQB", "YYJ",
    "YXE", "YQR", "YQT", "YXU", "YHM", "YKF", "YTZ", "YLW", "YYD", "YPR",
    "YXS", "YXT", "YZF", "YXY", "YQQ", "YAZ", "YZP", "YCD", "YBL", "YCG",
    "YKA", "YDL", "YNJ", "YXC", "YQL", "YMM", "YLL", "YGP", "YSJ", "YFC",
    "YAM", "YTS", "YQS", "YBR", "YDN", "YQA", "YPM", "YIN", "YRL", "YGX",
    "YTH", "YFO", "YKQ", "ZKE", "YHR", "YPX", "YGW", "YGL", "YVP", "YMT",
    "YAY", "YDF", "YQM", "YST", "YQX", "YJT", "YWK", "YYT", "YDP", "YWB",

    # Mexico
    "MEX", "CUN", "GDL", "MTY", "TIJ", "SJD", "MID", "PVR", "MZT", "BJX",
    "VER", "OAX", "TAP", "HUX", "ZIH", "CJS", "CUL", "HMO", "LAP", "MXL",
    "SLW", "DGO", "ZCL", "AGU", "SJO", "CEN", "CPE", "CME", "VSA", "CTM",
    "CZM", "MHC", "LOV", "PXM", "UPN", "CVM", "TAM", "REX", "MAM", "MFM",

    # Caribbean
    "NAS", "POS", "BGI", "ANU", "SXM", "STT", "STX", "SJU", "BQN", "PSE",
    "GCM", "KIN", "MBJ", "HAV", "VRA", "SNU", "CMW", "HOG", "SCU", "CCC",
    "SDQ", "POP", "STI", "JMB", "TAB", "GEO", "PBM", "PAP", "CAP", "JEE",
    "SKB", "NEV", "EIS", "VIJ", "AXA", "SFG", "BBR", "PTP", "FDF", "SBH",
    "SAF", "TUV", "BON", "CUR", "AUA", "GND", "SVD", "BQU", "SLU", "DOM",
    "DCF", "TOB", "TAB", "MQS", "BDA", "TCI", "LPA", "ACE", "TFN", "TFS",
    "SPC", "FUE", "PMI", "IBZ", "MAH",

    # Central America
    "SJO", "LIR", "XQP", "TTQ", "GMZ", "SAL", "GUA", "TGU", "RTB", "SAP",
    "MGA", "BEF", "RNI", "PTY", "DAV", "BOC", "CTD", "BLB", "MRS", "GHE",
    "GCM", "OCC", "MCM", "BZE",

    # South America
    "GRU", "GIG", "BSB", "SSA", "FOR", "REC", "POA", "CWB", "BEL", "MAO",
    "CGH", "SDU", "CNF", "FLN", "NAT", "JPA", "MCZ", "AJU", "THE", "BVB",
    "CGB", "CGB", "VCP", "CGR", "PMW", "PVH", "SLZ", "MCP", "IOS", "MOC",
    "IGU", "LDB", "JOI", "XAP", "NVT", "FLB", "ORI", "EZE", "AEP", "COR",
    "MDZ", "BRC", "BHI", "RSA", "PMQ", "REL", "RGA", "USH", "IGR", "SLA",
    "JUJ", "TUC", "CTC", "ROS", "SFN", "SCL", "PMC", "IQQ", "ANF", "ZCO",
    "TER", "CCP", "PMC", "LSC", "CPO", "ARI", "ZAL", "ZOS", "WCA", "MHC",
    "PMV", "BLA", "VLN", "MRD", "BRM", "MAR", "CCS", "STD", "EOZ", "GUQ",
    "CAJ", "PYH", "BOG", "MDE", "CLO", "CTG", "BAQ", "BGA", "PEI", "ADZ",
    "MTR", "UIB", "AXM", "OLV", "LPD", "EYP", "CZU", "NCI", "VVC", "APO",
    "LQM", "PCR", "ULQ", "SMR", "RCH", "IPI", "CUC", "EJA", "GPI", "CPB",
    "UCC", "TLU", "PSO", "ULQ", "LET", "EOH", "MZL", "PPN", "TME", "IBE",
    "LGT", "OCV", "RON", "HRR", "ACD", "NVA", "GAL", "ACM", "MVP", "PVA",
    "GIL", "LMC", "SOX", "LQM", "URI", "MQU", "GCA", "MTB", "CAQ", "COG",
    "LQT", "ORC", "PCR", "VGZ", "TBD", "BHF", "CUO", "NAR", "PLA", "HTZ",
    "LPE", "MFS", "MHF", "AZT", "REY", "SQE", "TCD", "VGD", "AML", "ELJ",
    "ECO", "MMP", "RVE", "DZI", "SRO", "TCO", "TQS", "NBB", "MND", "OTU",
    "SNT", "TLA", "LCR", "CFB", "GCC", "MUR", "CIM", "CUN", "GCA", "MHX",
    "API", "QSC", "LIM", "CUZ", "AQP", "TRU", "IQT", "PIU", "TCQ", "JUL",
    "PCL", "TPP", "TBP", "CIX", "SMG", "MBP", "ANS", "JAU", "HUU", "SQU",
    "AYP", "CJA", "CHM", "ATG", "UCZ", "IBP", "MFT", "NZC", "OBB", "RIM",
    "SQD", "SYC", "TDP", "UMI", "PMQ", "PHB", "GYE", "UIO", "OCC", "MEC",
    "CUE", "LTX", "MRR", "ATF", "SNL", "GPS", "TPN", "PBO", "TYL", "SCI",
    "MNU", "LIM", "CBB", "LPB", "SRE", "VVI", "TJA", "POI", "ORU", "BVK",
    "TDD", "RBO", "MQK", "RIB", "APB", "CEP", "SRZ", "MGD", "GYA", "POO",
    "BYC", "CIJ", "MOC", "CAM", "SNG", "BOY", "PUR", "ASC", "ANZ", "PSZ",
    "VAH", "MHW", "UAQ", "PVL", "MOQ", "REN", "SNR", "SBL", "TJQ", "LRU",
    "MVD", "PDP", "STY", "PYM", "MLZ", "DZO", "BUV", "MDO", "PDU", "ATI",
    "ANV", "TYT", "VCH", "CAR", "AGV", "BNS", "EOZ", "SFD", "LSP", "PMV",
    "TUV", "BLA", "CUM", "PPZ", "VLN", "CCS", "CXA", "GUQ", "MUN", "PZO",
    "SVZ", "STB", "VIG", "SOM", "CAJ", "GYI", "SKC", "KAI", "AHL", "BCG",
    "GEO", "IMB", "KKG", "LTM", "MHA", "MYM", "NAI", "OGL", "ORJ", "PKM",
    "QSX", "SKM", "TOO", "USI", "VEG", "WSB", "AJY", "PBM", "TOT", "DOE",
    "ICK", "KCB", "AGI", "KHW", "MOJ", "ORG", "PAM", "SMZ", "SMP", "SPB",

    # Europe - UK & Ireland
    "LHR", "LGW", "MAN", "STN", "LTN", "EDI", "BHX", "GLA", "BRS", "LPL",
    "NCL", "ABZ", "BFS", "CWL", "EXT", "SOU", "NQY", "BOH", "HUY", "MME",
    "LBA", "DSA", "JER", "GCI", "IOM", "BHD", "LDY", "DUB", "ORK", "SNN",
    "KIR", "NOC", "GWY", "CFN", "IIA", "WAT", "WEX", "FAO", "SXL", "CHF",

    # Europe - Western
    "CDG", "ORY", "NCE", "MRS", "LYS", "TLS", "BOD", "NTE", "SXB", "LIL",
    "MPL", "BIQ", "RNS", "BES", "LRH", "RDZ", "FNI", "PGF", "AJA", "BIA",
    "CFE", "CLY", "EGC", "FSC", "LBI", "LEH", "LIG", "MSN", "PIS", "POP",
    "QXB", "QXG", "QXN", "TUF", "URO", "VAF", "XCR", "XLN", "AMS", "EIN",
    "RTM", "GRQ", "MST", "BRU", "LGG", "ANR", "CRL", "OST", "LUX", "FRA",
    "MUC", "DUS", "TXL", "BER", "HAM", "STR", "CGN", "NUE", "LEJ", "HAJ",
    "BRE", "SCN", "DTM", "PAD", "FKB", "SXF", "ERF", "FMO", "HHN", "KSF",
    "MHG", "NRN", "RLG", "ZQW", "ZQC", "MAD", "BCN", "AGP", "ALC", "VLC",
    "SVQ", "BIO", "SCQ", "VGO", "OVD", "ZAZ", "GRX", "MJV", "XRY", "PMI",
    "IBZ", "MAH", "LPA", "TFN", "TFS", "ACE", "FUE", "SPC", "GMZ", "VDE",
    "SJZ", "SMA", "TER", "FLW", "HOR", "PIX", "PDL", "LIS", "OPO", "FAO",
    "FNC", "SID", "BVC", "RAI", "SFL", "SNE", "VXE", "MVA", "ZCO", "MHC",
    "FCO", "MXP", "LIN", "NAP", "CIA", "VCE", "CTA", "PMO", "BLQ", "PSA",
    "FLR", "TRN", "BGY", "VRN", "GOA", "TSF", "BRI", "CAG", "AHO", "OLB",
    "PMF", "PSR", "BDS", "REG", "SUF", "TRS", "TPS", "CIY", "CRV", "FRL",
    "AOI", "QCI", "RMI", "BZN", "BZO", "LMP", "PNL", "CRV", "EBA", "FGH",
    "IBL", "PRJ", "SAY", "ZOU", "ATH", "SKG", "HER", "RHO", "KGS", "CFU",
    "ZTH", "CHQ", "EFL", "JMK", "JTR", "KIT", "KSO", "MJT", "SKU", "SMI",
    "SOH", "AOK", "LXS", "LRS", "PVK", "JKH", "KLX", "JSH", "IOA", "PYR",
    "VOL", "KVA", "AXD", "AGQ", "GPA", "KZI", "LGK", "JNX", "JKL", "JAN",
    "GYD", "NAP", "KGD", "SIP", "DNK", "ODS", "HRK", "IEV", "KBP", "LWO",
    "KHE", "UMY", "VIN", "ZZO", "NLV", "RWN", "SBN", "CWC", "PLV", "ZPT",
    "BEG", "INI", "TIV", "TGD", "SKP", "PRN", "OHD", "SAR", "ZAG", "SPU",
    "DBV", "ZAD", "PUY", "LSZ", "BWK", "OSI", "SOU", "RJK", "BRQ", "PRG",
    "OSR", "KLV", "WAW", "KRK", "WRO", "POZ", "GDN", "KTW", "LCJ", "RZE",
    "BZG", "SZZ", "IEG", "BUD", "DEB", "PEV", "QGY", "SOB", "BTS", "KSC",
    "TAT", "PZY", "LZO", "ILZ", "OMO", "VIE", "GRZ", "INN", "KLU", "LNZ",
    "SZG", "HOB", "ZRH", "GVA", "BSL", "BRN", "LUG", "ACH", "GEN", "SIR",
    "OSL", "BGO", "TRD", "TOS", "BOO", "SVG", "KRS", "HAU", "MOL", "EVE",
    "SKE", "ALF", "AES", "ANX", "BDU", "BGY", "BJF", "BNN", "BVG", "DLD",
    "FAN", "FRO", "GAN", "HFT", "HMR", "HOV", "HVG", "KKN", "KSU", "LKN",
    "LKL", "MEH", "MJF", "MQN", "NTB", "NVK", "OLA", "ORL", "OSY", "RET",
    "RRS", "RVK", "RYG", "SDN", "SGJ", "SOG", "SOJ", "SSJ", "SRP", "STO",
    "SVJ", "THK", "VAW", "VDB", "VDS", "VRY", "XUZ", "CPH", "BLL", "AAL",
    "AAR", "ODE", "FAE", "GOH", "JAV", "SFJ", "UAK", "CNP", "JEG", "JFR",
    "JHS", "JJU", "JNS", "JOG", "JRK", "JTO", "JUV", "MFJ", "OGG", "PFK",
    "QFG", "QJI", "THU", "UMD", "ARN", "GOT", "MMX", "LLA", "UME", "OSD",
    "VXO", "NYO", "BMA", "KRN", "LDK", "GSE", "KSD", "KVB", "TYF", "SDL",
    "KLR", "AGH", "HFS", "HLF", "JKG", "HAD", "EVG", "MHQ", "HEL", "TMP",
    "TKU", "OUL", "RVN", "JOE", "KAO", "KEM", "KOK", "KUO", "MHQ", "SOT",
    "SVL", "TLL", "TAY", "RIX", "VNO", "KUN", "PLQ", "SQQ", "RZN", "LED",
    "SVO", "DME", "VKO", "SHE", "CEE", "KGD", "MMK", "ARH", "KZN", "BKA",
    "ROV", "AER", "OVB", "SVX", "UFA", "IKT", "KJA", "OMS", "TYA", "UUD",
    "VVO", "YKS", "PKC", "HTA", "BTK", "IRM", "KHV", "MJZ", "NER", "NOZ",
    "ODO", "OHH", "TLK", "UKX", "UUS", "HMA", "GOJ", "CEK", "PEE", "REN",
    "SGC", "TJM", "KRR", "STW", "MRV", "NAL", "OGZ", "VLK", "VLU", "GDZ",
    "MCX", "USK", "LDG", "UEN", "AMQ", "AZN", "CSY", "HEH", "IAR", "IGT",
    "KVX", "NYM", "NYA", "PYJ", "RGK", "SLY", "SWT", "TOF", "TRZ", "TXL",
    "UHH", "URS", "VRI", "XAB", "YEI", "ZIA", "ZKP", "ZTB",

    # Europe - Eastern
    "BKK", "WAW", "KRK", "BEG", "INI", "SOF", "BOJ", "VAR", "PDV", "BUH",
    "OTP", "CND", "SUJ", "CLJ", "IAS", "CRA", "TSR", "SBZ", "BCM", "BAC",
    "KIV", "OMO", "RMF", "TGD", "TIV", "VTB", "MSQ", "GME",

    # Middle East
    "DXB", "AUH", "SHJ", "AAN", "RKT", "DWC", "AMM", "AQJ", "BEY", "BGW",
    "BSR", "EBL", "ISU", "NJF", "OSM", "TBZ", "THR", "IKA", "ABD", "AWZ",
    "AHU", "ADU", "AEU", "AKW", "BXR", "CKT", "DCT", "DEF", "GBT", "GZW",
    "HDM", "IFH", "IIL", "JAB", "JAR", "KER", "KHD", "KIH", "KSH", "KHK",
    "LFM", "MHD", "MRX", "NOW", "OMH", "PFQ", "PGU", "QFB", "RAS", "SYJ",
    "TCX", "YES", "ZBR", "ZAH", "ACH", "ACZ", "ADM", "ADW", "AEF", "AFZ",
    "KWI", "DOH", "BAH", "MCT", "SLL", "DQM", "AOM", "LKH", "MSH", "OHS",
    "RNM", "STT", "SUH", "TTD", "UAS", "ACC", "RUH", "JED", "DMM", "MED",
    "TIF", "TUU", "AHB", "ABT", "HAS", "EAM", "GIZ", "HOF", "HBT", "JUI",
    "KMC", "MKX", "NBE", "NJH", "QNH", "RAE", "SHW", "TUI", "WAE", "YNB",
    "SAN", "SAF", "ADE", "TAI", "MYN", "ASL", "BHN", "DAH", "DMR", "EAB",
    "GXF", "HOD", "IHN", "LDR", "MFY", "RIY", "SCT", "SYE", "UKR", "WDA",
    "AAX", "AAY", "ABK", "AZR",

    # Africa
    "CAI", "HRG", "SSH", "LXR", "ASW", "RMF", "ATZ", "HBH", "ABS", "TCP",
    "AAE", "ABJ", "ACC", "ADD", "ADJ", "ALG", "ANR", "AOK", "AUE", "BAJ",
    "BCT", "BCX", "BEW", "BJL", "BKO", "BLZ", "BZV", "CKY", "CMN", "COO",
    "CRK", "DAK", "DAR", "DKR", "DLA", "DSS", "DZA", "EBB", "ENT", "FNA",
    "FIH", "GAB", "GAE", "GBE", "GOA", "HAH", "IBB", "IHO", "ILG", "JIB",
    "JNB", "KAN", "KDO", "KGL", "KHO", "KIS", "KMO", "KRT", "KWE", "LAD",
    "LFW", "LIL", "LOS", "LUN", "LXA", "MJI", "MJN", "MKS", "MLA", "MLW",
    "MMO", "MPN", "MPM", "MRU", "MRZ", "MSZ", "MTS", "MVB", "MYC", "MZO",
    "NBO", "NDJ", "NIM", "NKC", "NKW", "NLA", "OAL", "OLF", "ORN", "OUA",
    "OXB", "PHC", "PIK", "PKG", "PLJ", "PNR", "POD", "POG", "PTG", "PZB",
    "RAI", "RAK", "RBA", "ROB", "RUN", "SAP", "SAT", "SFJ", "SID", "SIS",
    "SMA", "SMV", "SRX", "SSG", "STO", "SYK", "SZK", "TBJ", "TIP", "TLE",
    "TNG", "TNR", "TOE", "TUN", "UAQ", "UIO", "VFA", "VIL", "WAD", "WDH",
    "XOG", "YAO", "ZNZ", "ZZU", "CPT", "DUR", "PLZ", "ELS", "BFN", "GRJ",
    "KIM", "MQP", "NLP", "PTG", "UTN", "AGJ", "BIY", "GCJ", "GRZ", "HLA",
    "JNB", "MGK", "MQP", "NTY", "OUH", "PCF", "PRY", "SIS", "SZK", "TCU",
    "UTW", "VRE", "VYD", "WEL", "WBO",

    # Asia - East
    "PEK", "PVG", "SHA", "CAN", "SZX", "CTU", "CKG", "XMN", "NKG", "HGH",
    "WUH", "TSN", "TAO", "XIY", "KMG", "CSX", "HRB", "SHE", "DLC", "TNA",
    "CGO", "LHW", "NGB", "URC", "LXA", "TFU", "FOC", "HET", "KWL", "KHN",
    "INC", "NNG", "SYX", "ZUH", "NNY", "WNZ", "JJN", "BAV", "BHY", "CGD",
    "CGQ", "CHG", "CIF", "CIH", "CZX", "DAT", "DAX", "DBC", "DDG", "DIG",
    "DOY", "DSN", "ENH", "ENY", "ERL", "ETR", "GHN", "GOQ", "GYS", "HAK",
    "HED", "HFE", "HJJ", "HLD", "HPG", "HSN", "HUZ", "IDO", "IQM", "IQN",
    "JGD", "JGN", "JHG", "JIC", "JIK", "JIL", "JIU", "JMU", "JNG", "JNZ",
    "JUZ", "JXA", "JYA", "KCA", "KHG", "KJI", "KRL", "KRY", "LCX", "LDS",
    "LHW", "LJG", "LLB", "LNJ", "LPF", "LQS", "LXA", "MIG", "MXZ", "NAO",
    "NDG", "NNY", "NTG", "OHE", "OMF", "OMH", "PKX", "PZI", "RIZ", "RKZ",
    "RLK", "SHS", "SQD", "SQJ", "TCG", "TCZ", "TGO", "THQ", "TLQ", "TVS",
    "TXN", "URC", "UTC", "UYN", "VIS", "WDS", "WEF", "WEH", "WHU", "WNH",
    "WUA", "WUH", "WUX", "WUZ", "WXN", "XIL", "XIN", "XNH", "XNN", "XUZ",
    "YBP", "YCU", "YIC", "YIH", "YIN", "YIW", "YNJ", "YNT", "YNZ", "YTY",
    "ZAT", "ZGC", "ZHA", "ZHY", "ZIY", "ZQZ", "ZYI", "HKG", "MFM", "TPE",
    "TSA", "KHH", "RMQ", "TNN", "TTT", "MZG", "CMJ", "HCN", "PIF", "KYD",
    "GNI", "WOT", "SEL", "ICN", "GMP", "PUS", "TAE", "CJJ", "CJU", "KWJ",
    "MWX", "RSU", "WJU", "YEC", "YNY", "KPO", "HIN", "USN", "NRT", "HND",
    "KIX", "NGO", "CTS", "FUK", "OKA", "SPK", "HIJ", "OKJ", "KOJ", "NGS",
    "OIT", "KMI", "MYJ", "TAK", "KMQ", "AXT", "MSJ", "HNA", "AKJ", "MMB",
    "IKI", "TNE", "KUH", "SHB", "WKJ", "HAC", "TKN", "OKE", "ISG", "UBJ",
    "IZO", "KCZ", "TKS", "IBR", "HHE", "FSZ", "TOY", "UBJ", "AOJ", "GAJ",
    "SYO", "SDJ", "FKS", "FKJ", "KIJ", "MMJ", "MYE", "NKM", "OKI", "TGO",
    "UBJ", "KMJ", "QCB", "ABJ", "WOK", "MUE", "CKG", "PKU",

    # Asia - Southeast
    "BKK", "DMK", "CNX", "HKT", "CEI", "NST", "UTP", "HDY", "KBV", "TST",
    "UBP", "KKC", "UDN", "NAK", "USM", "PHS", "MAQ", "TDX", "UTH", "SNO",
    "KOP", "PXR", "ROI", "VHM", "BFV", "KDT", "PYY", "LOE", "AXV", "CJM",
    "SGN", "HAN", "DAD", "CXR", "PQC", "VCA", "VII", "HPH", "DIN", "HUI",
    "BMV", "TBB", "DLI", "UIH", "VCS", "VDH", "KGL", "VKG", "VTE", "PKZ",
    "LPQ", "ODY", "OUI", "PCQ", "NEU", "SND", "THK", "ZBY", "ZVK", "PNH",
    "REP", "KZD", "KZK", "MWV", "OMY", "KOS", "TNX", "RGN", "MDL", "BMO",
    "KHM", "MGZ", "MNU", "MON", "MYT", "NYT", "PAA", "PKK", "PXU", "SNW",
    "TVY", "VBA", "VBP", "KUL", "SZB", "PEN", "BKI", "KCH", "LBU", "MYY",
    "BTU", "BKM", "SDK", "LAD", "LSM", "LKH", "JHB", "SIN", "MNL", "CEB",
    "DVO", "ILO", "KLO", "LAO", "GES", "PPS", "TDG", "ZAM", "BXU", "BCD",
    "CYZ", "DGT", "ENI", "GNI", "IGN", "JOL", "KAL", "KLO", "MPH", "MXI",
    "SUG", "TAG", "WNP", "CGK", "SUB", "MES", "BPN", "DPS", "HLP", "JOG",
    "MDC", "UPG", "LOP", "SOC", "BTH", "PDG", "PGK", "TKG", "TTE", "AMQ",
    "KNO", "PLM", "SRG", "BDJ", "SRI", "PKU", "PKY", "GNS", "DUM", "EOE",
    "EWE", "FKQ", "INX", "LLO", "LPU", "MCZ", "MKQ", "MKW", "MTQ", "NAH",
    "NBX", "OKQ", "RAQ", "RDE", "SEQ", "SQN", "SQQ", "SRJ", "STW", "TIM",
    "TMH", "TMY", "TTR", "WAR", "WGP", "WNI", "OGN", "RNU", "VXE", "VEL",

    # Asia - South
    "DEL", "BOM", "MAA", "CCU", "BLR", "HYD", "COK", "AMD", "PNQ", "GOI",
    "TRV", "IXB", "IXM", "PAT", "BBI", "LKO", "JAI", "ATQ", "VNS", "GAU",
    "VTZ", "IMF", "IXC", "IXR", "IXE", "RPR", "IXA", "SXR", "RJA", "IXH",
    "IXI", "IXL", "IXN", "IXP", "IXQ", "IXS", "IXU", "IXW", "IXY", "IXZ",
    "IXD", "IXG", "IXJ", "IXK", "IXV", "AGX", "BHO", "BHU", "BKB", "BLH",
    "BUB", "CDZ", "DHM", "DIB", "DIU", "GDB", "GUX", "HBX", "HGI", "HIR",
    "HJR", "HKD", "HSS", "ISK", "JAB", "JLR", "JRH", "JRG", "JTO", "KDH",
    "KEJ", "KLH", "KNB", "KNU", "KQH", "LUH", "MYQ", "NDC", "NIT", "OMO",
    "PAB", "PGH", "PNY", "PUT", "ROU", "RRK", "RTU", "SAG", "SHL", "SIX",
    "SLV", "SSE", "TEI", "TEN", "THR", "TJV", "TNI", "TRZ", "UDR", "UEP",
    "VBS", "VGA", "VNS", "VYD", "WGC", "ZER", "DAC", "CGP", "JSR", "ZYL",
    "KMG", "BHW", "RJH", "SPD", "CXB", "GBT", "HEA", "JAA", "KBL", "KDH",
    "KHT", "KDH", "MZR", "OAH", "OAI", "SGA", "TII", "UND", "UND", "URZ",
    "ZAJ", "CMB", "DRZ", "HRI", "JAF", "KCT", "KTM", "PKR", "BWA", "BIR",
    "JMO", "LUA", "KEP", "MWP", "PPL", "RHP", "SKH", "TMI", "TPJ", "TIA",
    "BIK", "KYE", "MWX", "GWD", "ISB", "LHE", "KHI", "UET", "PEW", "SKT",
    "LYP", "MUX", "KDU", "GIL", "ATG", "MFG", "PSI", "RYK", "SBQ", "SUL",
    "TUK", "WNS", "BHV", "CJL", "DSK", "EDW", "PJG", "SYW", "ZIZ", "OHT",
    "ORW", "MGQ", "BQS", "BQE", "BQH", "BQK", "BQN",

    # Asia - Central
    "ALA", "TSE", "AKX", "ATX", "DMB", "DZN", "GUW", "HRC", "KGF", "KSN",
    "KZO", "ORA", "PPK", "PWQ", "URA", "UUU", "FRU", "OSS", "AKO", "IKU",
    "KMV", "TAS", "NVI", "NCU", "KSQ", "AZN", "SKD", "BHK", "FEG", "KMQ",
    "NMA", "UGC", "ZAF", "DUS", "ASB", "KRW", "MYP", "TAZ", "TGN", "TZO",
    "DYU", "LBD", "KQT", "KHG", "FRU",

    # Oceania
    "SYD", "MEL", "BNE", "PER", "ADL", "OOL", "CNS", "CBR", "HBA", "TSV",
    "MKY", "LST", "HTI", "ROK", "MCY", "PPP", "BME", "BWT", "CED", "DBO",
    "DKI", "DRW", "EDR", "EPR", "GFF", "GOV", "GSC", "GTE", "GYP", "HGD",
    "INJ", "IOR", "ISA", "KNS", "KTR", "LDC", "LEA", "LNO", "LRE", "LSY",
    "LVO", "MBH", "MCV", "MEB", "MIM", "MJK", "MNG", "MQL", "MRZ", "MYA",
    "NAA", "NIF", "NLK", "NSM", "NSO", "NTL", "NTN", "NUB", "OAG", "OBB",
    "OCM", "ORR", "ORS", "OXY", "PBO", "PDE", "PHE", "PKE", "PLO", "PPI",
    "PQQ", "PRD", "QCN", "RMA", "RMK", "ROB", "RPB", "RRE", "RTS", "SHU",
    "SQC", "SSK", "SWC", "TCW", "TEM", "TER", "TGN", "TMW", "TPR", "TRO",
    "UDA", "UIR", "WDI", "WEI", "WIN", "WKB", "WMB", "WNR", "WPK", "XTO",
    "AKL", "CHC", "WLG", "ZQN", "NSN", "DUD", "HLZ", "ROT", "PMR", "NPL",
    "KKE", "KAT", "GIS", "TRG", "WHO", "NPE", "IVC", "BHE", "WSZ", "MFN",
    "OAM", "WRE", "TKZ", "WIK", "HKK", "KBZ", "GBZ", "ATI", "SUA", "PPT",
    "FAA", "MOZ", "BOB", "RFP", "RGI", "MKP", "TIH", "FHZ", "AAA", "APK",
    "AEH", "FGU", "GMR", "KHZ", "MAU", "MKP", "MVT", "NAU", "NHV", "NIU",
    "PKP", "PUK", "RRR", "TKP", "TKX", "UAH", "UAP", "ULI", "VHZ", "XMH",
    "HIR", "GZO", "MUA", "MBU", "AKS", "RUS", "VAO", "EGM", "RBV", "SCZ",
    "ATD", "AFT", "ANH", "BNY", "CHY", "GTA", "IRA", "KGE", "KSH", "KWR",
    "KWS", "MBU", "NAZ", "NGI", "OTV", "PAV", "PRS", "RNA", "RNL", "SAS",
    "VEV", "XYA", "TBU", "VAV", "NTF", "EUA", "HPA", "APW", "FTI", "MXS",
    "PPG", "RUR", "SAV", "SDN", "SGO", "FUT", "IUE", "KEF", "NAN", "SUV",
    "TVU", "MFJ", "LBS", "PHR", "PTF", "RTA", "KDV", "VBV", "BXL", "ONU",
    "YAS", "AYY", "CST", "ICI", "KAY", "KXF", "LKB", "LUC", "NGD", "OBI",
    "OCV", "RBT", "RGO", "SSO", "TTL", "VBQ", "VRN", "VTF", "VUN", "LML",
    "POM", "WWK", "HGU", "LAE", "RAB", "UNG", "GKA", "MDU", "LSA", "MAG",
    "MAS", "MXH", "KMA", "MIS", "NKN", "ORE", "POM", "POM", "TBG", "TIZ",
    "TIZ", "TWY", "UAQ", "UNG", "VAI", "VMU", "WBM", "WEW", "WNU", "WOA",
    "WSD", "WSK", "DRH", "ABP", "AEK", "AFR", "AGK", "AIE", "AIO", "AKG",
    "AOB", "AWB", "AYU", "AZB", "BAA", "BDZ", "BKL", "BPD", "BPK", "CDR",
    "CIG", "CMU", "COE", "COH", "CPI", "CVL", "CVB", "CWA", "DAF", "DAU",
    "DBP", "DER", "DGB", "DGN", "DOO", "EMI", "ERE", "ESA", "ETI", "FAQ",
    "FIN", "FUM", "FUV", "FXM", "GAR", "GBC", "GBF", "GEI", "GEW", "GHL",
    "GKA", "GMI", "GNU", "GOC", "GOE", "GRL", "GUR", "HYF", "IBI", "IHU",
    "IMD", "IOK", "IOP", "IPN", "IRU", "IUS", "IWA", "JAQ", "KBM", "KDR",
    "KEB", "KGM", "KIZ", "KJU", "KKD", "KKP", "KMR", "KRJ", "KSB", "KUP",
    "KUQ", "KWO", "KWV", "LGN", "LKN", "LMI", "LMY", "LNF", "LPD", "LPN",
    "LWI", "MAS", "MBT", "MCV", "MDN", "MGP", "MRM", "MTK", "MWG", "MXK",
    "MYE", "MZN", "NDN", "NIS", "NKN", "NOM", "NPG", "OGE", "OKV", "OLQ",
    "OMO", "OPB", "OSE", "OSG", "PGN", "PLE", "PMN", "PMP", "PNP", "POL",
    "PUI", "PUM", "PUS", "RMH", "RUU", "SMH", "SMJ", "SMP", "SPV", "SQT",
    "SSS", "SWE", "SWG", "TBQ", "TDS", "TFM", "TGL", "TKB", "TKW", "TLP",
    "TON", "TQJ", "TRS", "TSW", "TUJ", "TUK", "TUT", "UBI", "ULE", "UMC",
    "UPR", "URI", "UUU", "VAO", "VEO", "VIV", "VMU", "WKW", "WLK", "WOM",
    "WSA", "WUG", "XBN", "YVD", "ZEN",

    # Japan additional
    "HND", "NRT", "KIX", "NGO", "CTS", "FUK", "OKA", "HIJ", "SDJ", "NGS",
    "KOJ", "OIT", "KMI", "MYJ", "TAK", "AXT", "MSJ", "HNA", "AKJ", "MMB",
    "SHB", "WKJ", "HAC", "TKN", "OKE", "ISG", "UBJ", "IZO", "KCZ", "TKS",
    "IBR", "HHE", "FSZ", "TOY", "GAJ", "SYO", "FKS", "FKJ", "KIJ",
}


def is_valid_airport_code(code: str) -> bool:
    """
    Returns True if the given string is a known IATA airport code.
    Accepts both upper and lower case input.
    """
    if not code or not isinstance(code, str):
        return False
    return code.upper().strip() in VALID_AIRPORT_CODES


def normalize_airport_code(code: str) -> str:
    """
    Normalizes an airport code to uppercase stripped form.
    Raises ValueError if the code is not valid.
    """
    normalized = code.upper().strip()
    if normalized not in VALID_AIRPORT_CODES:
        raise ValueError(f"'{code}' is not a recognized IATA airport code.")
    return normalized