import { test, expect } from "@playwright/test";
test("ownership fork b2 renders on points verdict", async ({ page }) => {
	test.setTimeout(300_000);
	await page.goto("/home");
	await page.addStyleTag({ content: "*,*::before,*::after{animation:none!important;transition:none!important}" });
	const d = page.locator('input[type="date"]');
	await d.nth(0).fill("2026-12-25");
	await d.nth(1).fill("2027-01-09");
	const a = page.locator('input[placeholder="City or airport"]');
	await a.nth(0).fill("SFO"); await a.nth(0).press("Enter");
	await a.nth(1).fill("SIN"); await a.nth(1).press("Enter");
	await page.getByTestId("more-options-toggle").click();
	await page.locator("select").nth(2).selectOption("premium_economy");
	const rp = page.waitForResponse((r) => r.url().includes("/api/search") && r.request().method() === "POST", { timeout: 180_000 });
	await page.getByRole("button", { name: /Search Flights/ }).click();
	const body = await (await rp).json();
	const own = body?.verdict?.ownership, mm = body?.verdict?.metrics, ww = body?.verdict?.winner;
	console.log("REC", body?.verdict?.recommendation, "RETURN_AWARDS", (body?.return_award_options||[]).length, "SCOPE", body?.verdict?.metrics?.scope, "COMPARISON", body?.verdict?.metrics?.comparison_cash);
	console.log("WINNER_PTS(outbound/pax)", ww?.points, "METRICS_PTS(fulltrip)", mm?.points_cost, "CPP", mm?.cpp);
	console.log("OWN_needed", own?.points_needed, "OWN_afford", own?.can_afford, "OWN_short", own?.shortfall);
	await page.waitForTimeout(7000);
	const fork = page.getByTestId("ownership-fork");
	await fork.scrollIntoViewIfNeeded().catch(() => {});
	const visible = await fork.isVisible().catch(() => false);
	console.log("FORK_VISIBLE", visible, "FORK_STATE", await fork.getAttribute("data-fork").catch(() => null));
	console.log("FORK_TEXT", (await fork.textContent().catch(() => ""))?.slice(0, 260));
	console.log("TRADE_LINE", (await page.getByTestId("verdict-honesty-line").textContent().catch(() => null)));
	expect(visible).toBe(true);
	await page.screenshot({ path: "playwright/.artifacts/fork-restored.png", fullPage: false });
});
