"""
rag/kb/sweet_spots.py
──────────────────────
The definitive guide to the best points redemptions in travel.
Sweet spots are award rates where the value per point is exceptional —
typically 3cpp or higher.

CATEGORY: award_tools
VALID AS OF: 2026-Q2
"""

from __future__ import annotations

SWEET_SPOTS_KB: list[dict] = [

    {
        "id": "sweet-spots-master-list",
        "title": "The 30 Best Points Redemptions in Travel — Master Sweet Spot Guide",
        "category": "award_tools",
        "tags": ["sweet spots", "best redemptions", "CPP", "business class", "first class", "award value"],
        "valid_as_of": "2026-Q2",
        "summary": "The definitive list of the best points redemptions ranked by value. Top spots: Virgin Atlantic → ANA Business (7-10 cpp), Alaska → Emirates First (5-8 cpp), Iberia → Transatlantic Business (4-6 cpp), AAdvantage → JAL First (5-8 cpp). All require finding award availability first.",
        "content": (
            "Sweet spots are specific program+route combinations where points deliver exceptional value — typically 3+ cents per point. "
            "These are the redemptions experienced points travelers prioritize.\n\n"
            "TIER 1 — EXCEPTIONAL (5+ cpp regularly achievable):\n\n"
            "1. VIRGIN ATLANTIC → ANA BUSINESS CLASS (US-JAPAN)\n"
            "Miles needed: ~60,000-65,000 one-way\n"
            "Cash value: $5,000-$8,000 for ANA The Room (best business class product)\n"
            "CPP: 7-12 cpp\n"
            "How: Call Virgin Atlantic, request ANA (NH) partner award. Transfer Chase UR, Amex MR, Citi TY, or Bilt to Virgin.\n"
            "Why it's special: ANA The Room on the 777-300ER is one of the best business class products ever built. 60,000 miles for a $6,000 seat is extraordinary. No fuel surcharges.\n"
            "Availability: Limited but findable. Best at 355 days out or 1-3 months before departure.\n\n"
            "2. ALASKA → EMIRATES FIRST CLASS (US-DUBAI/LONDON)\n"
            "Miles needed: ~85,000-110,000 one-way\n"
            "Cash value: $10,000-$20,000+ for Emirates First Suite with shower\n"
            "CPP: 9-20 cpp\n"
            "How: Search alaskaair.com for Emirates (EK) awards. Transfer via Bank of America Alaska card spend.\n"
            "Why it's special: Emirates charges $600-$1,200 in surcharges via Skywards. Alaska charges only $30-$80 in government taxes. Same shower and Dom Perignon — different fee structure.\n"
            "Availability: Varies significantly by route and date. DXB routes from JFK and LAX typically have the most space.\n\n"
            "3. AADVANTAGE → JAL FIRST CLASS (US-JAPAN)\n"
            "Miles needed: ~80,000-110,000 one-way\n"
            "Cash value: $10,000-$18,000 for JAL First Class Suites\n"
            "CPP: 9-15 cpp\n"
            "How: aa.com or call AA. Book JAL (JL) first class flights. Transfer Citi TY to AA.\n"
            "Why it's special: JAL First Class is one of the finest experiences in commercial aviation. 110,000 AAdvantage miles one-way NRT-JFK for a $15,000 seat is among the best first class redemptions available to US travelers.\n"
            "Availability: JAL releases first class award space regularly via AAdvantage. Search 355 days out.\n\n"
            "4. IBERIA AVIOS → TRANSATLANTIC BUSINESS CLASS (OFF-PEAK)\n"
            "Miles needed: 34,000 Avios one-way (off-peak)\n"
            "Cash value: $2,500-$5,000 for Iberia business class JFK/EWR/BOS-MAD/BCN\n"
            "CPP: 7-15 cpp\n"
            "How: Book on iberia.com using Iberia Plus account. Transfer Chase UR or Amex MR to Iberia Plus.\n"
            "Why it's special: 34,000 Avios is remarkably cheap for transatlantic business class. Low fuel surcharges (~$100-150 vs BA's $400-800). Iberia's A330 business class is good, food is excellent, service warm.\n"
            "Availability: Generally good — Iberia manages its own award inventory.\n\n"
            "5. UNITED → LUFTHANSA FIRST CLASS (TRANSATLANTIC)\n"
            "Miles needed: ~110,000-143,000 one-way\n"
            "Cash value: $8,000-$15,000\n"
            "CPP: 5-10 cpp\n"
            "How: Search united.com for Lufthansa (LH) first class. Transfer Chase UR to United.\n"
            "Why it's special: Lufthansa First Class includes access to the Frankfurt First Class Terminal — a private terminal with gourmet dining, spa, and private car to aircraft. Unique experience not replicated anywhere.\n"
            "Availability: Lufthansa releases first class space to Star Alliance partners starting 15 days before departure. Be flexible and monitor close-in.\n\n"
            "TIER 2 — EXCELLENT (3-5 cpp regularly achievable):\n\n"
            "6. VIRGIN ATLANTIC → DELTA ONE TRANSATLANTIC\n"
            "Miles needed: ~50,000 one-way\n"
            "Cash value: $2,000-$5,000 Delta One\n"
            "CPP: 4-8 cpp\n"
            "How: virginatlantic.com, book Delta (DL) flights. Transfer Chase UR, Amex MR, Citi TY, or Bilt.\n\n"
            "7. ALASKA → JAL BUSINESS CLASS (US-JAPAN)\n"
            "Miles needed: ~55,000 one-way\n"
            "Cash value: $4,000-$8,000 JAL business class\n"
            "CPP: 7-12 cpp\n"
            "How: alaskaair.com, book JAL (JL) awards. No fuel surcharges.\n\n"
            "8. AIR CANADA AEROPLAN → LUFTHANSA/SWISS BUSINESS (TRANSATLANTIC)\n"
            "Miles needed: ~60,000-75,000 one-way\n"
            "Cash value: $3,000-$8,000\n"
            "CPP: 4-10 cpp\n"
            "How: aeroplan.com. No fuel surcharges on Lufthansa via Aeroplan (small handling fee only). Transfer Chase UR, Amex MR, Capital One.\n\n"
            "9. FLYING BLUE PROMO → TRANSATLANTIC BUSINESS (AF/KLM)\n"
            "Miles needed: 40,000-60,000 one-way (during promo, normally 80,000+)\n"
            "Cash value: $3,000-$6,000\n"
            "CPP: 5-12 cpp during promos\n"
            "How: Check flyingblue.com on 1st of each month. Book quickly — promos sell out.\n\n"
            "10. ALASKA → CATHAY PACIFIC BUSINESS CLASS\n"
            "Miles needed: ~50,000-65,000 one-way (US-HKG)\n"
            "Cash value: $4,000-$7,000\n"
            "CPP: 6-10 cpp\n"
            "How: alaskaair.com, book Cathay (CX) awards. No fuel surcharges.\n\n"
            "11. AADVANTAGE → BRITISH AIRWAYS BUSINESS (AA Metal — No Surcharges)\n"
            "Miles needed: ~50,000-57,500 one-way\n"
            "Cash value: $2,500-$5,000\n"
            "CPP: 4-7 cpp\n"
            "How: Book AA-operated transatlantic flights via aa.com. No BA surcharges because AA is operating.\n\n"
            "12. CHASE UR → HYATT LUXURY HOTELS\n"
            "Miles needed: 25,000-45,000 Hyatt points (transfer 1:1 from Chase UR)\n"
            "Cash value: $300-$800+/night at Park Hyatt, Andaz, Alila properties\n"
            "CPP: 1.2-3.0 cpp\n"
            "Why it's special: Consistency. Hyatt is always a reliable, high-value transfer that beats the 1.5cpp Chase Travel portal.\n\n"
            "13. TURKISH MILES&SMILES → BUSINESS CLASS TO JAPAN/EUROPE\n"
            "Miles needed: ~45,000-70,000 one-way business class (historically — verify current)\n"
            "Cash value: $3,000-$8,000\n"
            "CPP: 4-10 cpp\n"
            "How: turkishairlines.com, book Star Alliance partners. Transfer Capital One or Citi.\n"
            "Caveat: Booking process is complex, website can be unreliable, phone booking often necessary.\n\n"
            "14. AVIANCA LIFEMILES → BUSINESS CLASS (STAR ALLIANCE PARTNERS)\n"
            "Miles needed: Variable, often lower than other programs for Star Alliance\n"
            "Cash value: $2,000-$7,000 depending on route\n"
            "CPP: 3-6 cpp\n"
            "Why it works: LifeMiles flash sales periodically offer cheap mile purchases (often 1.3-1.5 cents/mile) + low award rates on partners = stacked value.\n\n"
            "15. ALASKA → FINNAIR BUSINESS CLASS\n"
            "Miles needed: ~50,000 one-way (Europe)\n"
            "Cash value: $2,500-$4,000\n"
            "CPP: 5-8 cpp\n"
            "No fuel surcharges. Finnair has good European business class on long routes.\n\n"
            "TIER 3 — GOOD DOMESTIC AND REGIONAL:\n\n"
            "16. UNITED → HAWAII ECONOMY (WEST COAST)\n"
            "Miles: 12,500 one-way | Cash: $250-$500 | CPP: 2-3 cpp\n\n"
            "17. HYATT → PARK HYATT/ANDAZ (ANY TOP PROPERTY)\n"
            "Points: 25,000-45,000 | Cash: $400-$1,500 | CPP: 1.6-4.0 cpp\n\n"
            "18. SOUTHWEST + COMPANION PASS (DOMESTIC)\n"
            "Points: Standard award rates + companion flies free = effective CPP doubles for companion\n\n"
            "19. ALASKA → AMERICAN METAL DOMESTIC (FIXED CHART)\n"
            "Miles: 7,500 one-way (under 500 miles) | Fixed rates for all cabin classes\n\n"
            "20. FLYING BLUE → KENYA/AFRICA (PROMO)\n"
            "Miles: 30,000-50,000 one-way business during promo | Cash: $3,000-$5,000\n"
            "CPP: 6-10 cpp during promo periods\n\n"
            "HOW TO USE THIS LIST:\n"
            "1. Identify which transferable currencies you have (Chase UR, Amex MR, etc.)\n"
            "2. Match to the sweet spot programs they feed\n"
            "3. Check availability BEFORE transferring\n"
            "4. Transfer only once availability is confirmed\n"
            "5. Book immediately after transfer clears\n\n"
            "GOLDEN RULES OF SWEET SPOTS:\n"
            "- Sweet spots disappear. Programs devalue. Always book sooner rather than later.\n"
            "- Verify award space exists before transferring — transfers are irreversible\n"
            "- The best redemptions require flexibility on dates\n"
            "- Business class sweet spots outperform economy 3-5x in cpp — always evaluate the premium cabin"
        ),
    },

    {
        "id": "transfer-bonus-history-guide",
        "title": "Transfer Bonus History and Strategy — When to Transfer Points",
        "category": "award_tools",
        "tags": ["transfer bonus", "Amex transfer bonus", "Flying Blue bonus", "Virgin Atlantic bonus", "Singapore bonus", "timing"],
        "valid_as_of": "2026-Q2",
        "summary": "Transfer bonuses add 20-50% extra miles when moving bank points to airline partners. Air France Flying Blue, Virgin Atlantic, and British Airways run the most frequent Amex bonuses. Chase runs fewer bonuses but Singapore KrisFlyer and United have appeared. Never transfer speculatively just for a bonus.",
        "content": (
            "Transfer bonuses are promotions where a bank currency (Chase UR, Amex MR, etc.) offers a bonus when transferring to a specific airline partner. "
            "A 30% bonus means 100,000 Amex MR → 130,000 Air France miles instead of 100,000.\n\n"
            "HISTORICAL TRANSFER BONUS FREQUENCY:\n\n"
            "AMEX MEMBERSHIP REWARDS — Most Frequent Bonus Partner:\n\n"
            "Air France/KLM Flying Blue: Runs Amex transfer bonuses 3-5 times per year, historically 25-40% bonus. This is the most frequent and most valuable bonus to watch for. When combined with Flying Blue Promo Awards, you can get exceptional value — fewer points transferred, then Promo reduces the award cost further.\n\n"
            "Virgin Atlantic Flying Club: Runs bonuses 2-3 times per year via Amex, typically 20-40%. Given Virgin's sweet spots (Delta One, ANA business), a 30% transfer bonus makes already-good redemptions even better.\n\n"
            "British Airways Executive Club: Periodic bonuses of 20-30%. Less frequent than Flying Blue. Useful if targeting Iberia/BA Avios redemptions.\n\n"
            "Singapore KrisFlyer: Occasional bonuses via Amex, typically 20-25%. Rarer than Flying Blue but valuable given Singapore's premium cabin sweet spots.\n\n"
            "ANA Mileage Club: Rare but has appeared. Watch for any bonus — ANA miles are hard to accumulate from the US.\n\n"
            "Hilton Honors (1:2 normally — bonus makes 1:2.5 or 1:3): Quarterly or more. When Hilton runs an Amex bonus AND Hilton has a points sale, can be a good time to stock up for specific redemptions.\n\n"
            "CHASE ULTIMATE REWARDS — Less Frequent:\n"
            "Chase runs transfer bonuses less often than Amex. When they appear:\n"
            "United MileagePlus: Has appeared at 25-30% periodically.\n"
            "Singapore KrisFlyer: Has run via Chase.\n"
            "World of Hyatt: Rare — Chase sometimes runs hotel transfer bonuses.\n"
            "British Airways Avios: Occasional Chase bonus.\n\n"
            "CAPITAL ONE — MODERATE FREQUENCY:\n"
            "Turkish Miles&Smiles: Capital One has run transfer bonuses to Turkish — notable given Turkish's low award rates for business class.\n"
            "Avianca LifeMiles: Occasional bonus from Capital One.\n"
            "Other partners: Various Capital One bonuses appear throughout the year.\n\n"
            "CITI THANKYOU — MODERATE FREQUENCY:\n"
            "Turkish Miles&Smiles: Citi runs Turkish bonuses periodically.\n"
            "Flying Blue: Occasional Citi bonus.\n"
            "Singapore: Rare but has appeared.\n\n"
            "HOW TO TRACK TRANSFER BONUSES:\n"
            "1. Check your Amex, Chase, and Capital One account transfer pages regularly — bonuses appear there.\n"
            "2. Subscribe to email alerts from The Points Guy, One Mile at a Time, Frequent Miler — they post bonuses immediately.\n"
            "3. Reddit r/awardtravel posts transfer bonuses in real time.\n"
            "4. Set a monthly reminder to check for Flying Blue Promo Awards AND transfer bonuses simultaneously.\n\n"
            "STACKING STRATEGY:\n"
            "The ultimate stack:\n"
            "1. Wait for Amex → Flying Blue transfer bonus (e.g., 40%)\n"
            "2. Transfer points during the bonus window\n"
            "3. Use the extra miles during a Flying Blue Promo Award month\n"
            "Example: 60,000 Amex MR → 84,000 Flying Blue miles (with 40% bonus)\n"
            "Then redeem 40,000 miles for transatlantic business during promo (normally 80,000)\n"
            "Net: 60,000 Amex MR for a $3,000-$5,000 transatlantic business class seat = 5-8 cpp\n\n"
            "CRITICAL WARNINGS:\n"
            "NEVER transfer points speculatively just because a bonus exists. If you don't have a specific confirmed award you're targeting:\n"
            "- Points should stay in your bank account (flexible, transferable to any partner)\n"
            "- Airline miles are siloed — can only be used for that airline's awards\n"
            "- Programs devalue — transferring 'for later' might mean the sweet spot is gone when you use them\n"
            "Only transfer when: Award space is confirmed + you're ready to book + the bonus makes the redemption noticeably better."
        ),
    },

    {
        "id": "points-earning-non-travel",
        "title": "Earning Points on Non-Travel Spend — Shopping Portals, Dining, and More",
        "category": "award_tools",
        "tags": ["shopping portal", "dining program", "airline dining", "points earning", "non-travel", "everyday spend"],
        "valid_as_of": "2026-Q2",
        "summary": "Airline shopping portals (United, Delta, American, Alaska) and dining programs earn bonus miles on everyday purchases at no extra cost. Portals offer 2-30+ miles per dollar at thousands of retailers. Dining programs earn 3-5 miles per dollar at participating restaurants.",
        "content": (
            "Earning points isn't limited to flights and credit cards. Shopping portals, dining programs, and partner spending can add thousands of miles per year with no incremental cost.\n\n"
            "AIRLINE SHOPPING PORTALS:\n"
            "Shopping portals sit between you and online retailers. Click through the portal before buying → earn bonus airline miles on your purchase (in addition to whatever your credit card earns).\n\n"
            "MAJOR PORTALS:\n"
            "United MileagePlus Shopping: Offers 1-30+ miles per dollar at thousands of retailers. Strong rates at Apple, Walmart, Target, Nike, Macy's, and others. Check before ANY online purchase.\n"
            "Delta SkyMiles Shopping: Similar scope. Strong at many major retailers.\n"
            "American AAdvantage eShopping: Broad retailer coverage, competitive rates.\n"
            "Alaska Mileage Plan Shopping: Good for West Coast-centric brands, expanding.\n"
            "Chase Ultimate Rewards Shopping: Some retailers offer bonus UR points.\n"
            "Rakuten: Not airline-specific, but transfers cash back to Amex MR via special Rakuten Amex card. One of the highest cash-back rates on the market.\n\n"
            "HOW TO MAXIMIZE PORTALS:\n"
            "1. Before any online purchase, go to cashbackmonitor.com or evreward.com — they compare ALL portal rates across all programs simultaneously\n"
            "2. Pick the portal offering the highest rate for that retailer on that day\n"
            "3. Click through, then complete your purchase normally\n"
            "4. Miles post within 2-6 weeks\n\n"
            "PORTAL MATH EXAMPLE:\n"
            "Buy $500 Nike shoes. Portal offers 12x United miles on Nike.\n"
            "Miles earned from portal: 6,000 United miles\n"
            "Plus 3x Chase Sapphire Reserve (purchases): 1,500 UR points\n"
            "Total: 7,500 miles/points from a single $500 purchase with zero extra effort\n\n"
            "AIRLINE DINING PROGRAMS:\n"
            "Register your credit card(s) with the program → earn miles automatically when dining at participating restaurants.\n\n"
            "UNITED MILEAGEPLUS DINING: Register cards, earn 3-5 miles per dollar at participating restaurants. First dining within 30 days earns a bonus (typically 1,000-3,000 extra miles).\n\n"
            "DELTA SKYMILES DINING: Same structure. 3-5 miles per dollar at participating locations.\n\n"
            "AMERICAN AADVANTAGE DINING: Participating restaurants in major cities. Earn 3+ miles per dollar.\n\n"
            "ALASKA MILEAGE PLAN DINING: Similar program.\n\n"
            "KEY DINING PROGRAM TIPS:\n"
            "- Register ALL your credit cards with the dining program — you might not always use your primary travel card at restaurants\n"
            "- The miles are additive — you earn portal miles PLUS credit card dining bonus (3x on Amex Gold + dining program = strong combination)\n"
            "- Dining programs rotate restaurants and deals — worth checking what's near you\n\n"
            "HOTEL PARTNER EARNING:\n"
            "Many hotel loyalty programs have airline mile earning options:\n"
            "- Convert hotel points to airline miles (generally poor value — e.g., 10,000 Marriott = 3,333 airline miles)\n"
            "- Pay with certain credit cards at hotels to earn miles via hotel's partnership with airline\n"
            "- Some hotels offer miles instead of hotel points when you choose at check-in\n"
            "Rule of thumb: Earning hotel points at hotels (not airline miles) is usually better — hotel points in their own program are worth more than the airline miles equivalent.\n\n"
            "CAR RENTAL EARNING:\n"
            "Major car rental companies partner with airline programs:\n"
            "- Hertz earns United, Delta, American, others (typically 500-1,000 miles per rental)\n"
            "- Avis earns United, Delta, American\n"
            "- National earns Delta and others\n"
            "- Enterprise earns Delta\n"
            "Always register your loyalty account with the rental company and enter your airline frequent flyer number at booking.\n\n"
            "CREDIT CARD ANNUAL BONUSES:\n"
            "Some cards give significant annual earning bonuses:\n"
            "- Hyatt card: 10% anniversary point bonus on prior year spend\n"
            "- Southwest cards: 6,000-9,000 anniversary bonus points\n"
            "- Chase Freedom Flex: 5x on rotating quarterly categories (gas, Amazon, grocery, etc.)\n"
            "These add up significantly over years of card holding.\n\n"
            "REFERRAL BONUSES:\n"
            "Most premium cards offer referral bonuses (5,000-30,000 points) when friends apply via your referral link and are approved. Credit card referral bonuses are taxable in some cases — consult a tax professional."
        ),
    },

    {
        "id": "alliance-routing-rules",
        "title": "Star Alliance, Oneworld, and SkyTeam Routing Rules for Award Travel",
        "category": "award_tools",
        "tags": ["Star Alliance", "Oneworld", "SkyTeam", "routing rules", "multi-city", "stopover", "open-jaw"],
        "valid_as_of": "2026-Q2",
        "summary": "Alliance routing rules allow complex multi-city award itineraries. United MileagePlus Excursionist Perk (free one-way within a round-trip). Aeroplan allows free stopover in Canada. AA allows open-jaw bookings. These rules can add destinations to your trip at no extra points cost.",
        "content": (
            "Understanding airline alliance routing rules unlocks multi-city itineraries — sometimes adding an entire extra destination at no incremental points cost.\n\n"
            "KEY TERMS:\n"
            "STOPOVER: Intentional connection of more than 24 hours in a city. You spend 1-3 days there before continuing.\n"
            "OPEN-JAW: Flying into City A, then departing from City B (without flying A→B). Example: fly JFK→London, then Paris→JFK. The London→Paris segment is a gap you arrange separately (train, bus, flight).\n"
            "ROUND-TRIP AWARD: Origin → Destination → Origin.\n"
            "ONE-WAY AWARD: Most programs price one-ways at 50% of round trip, though some price differently.\n\n"
            "UNITED MILEAGEPLUS — EXCURSIONIST PERK:\n"
            "When booking a multi-destination round-trip award, you can add one free one-way flight within a region. Example: JFK→Tokyo→Sydney→Singapore→JFK. United allows a free Tokyo→Sydney leg (within the Asia region) if the itinerary eventually returns to the origin.\n"
            "How to use: Build a round-trip itinerary with multiple destinations, and one connection within the same region is 'free' (uses the round-trip award rate, not extra miles).\n"
            "Best for: Asia itineraries combining Japan + Australia, or Europe itineraries adding a second European city.\n\n"
            "AIR CANADA AEROPLAN — FREE STOPOVER POLICY:\n"
            "Aeroplan allows one free stopover in Canada on round-trip awards. Example: LAX→Toronto→London and London→Toronto→LAX, with a 3-day stopover in Toronto in between. You pay only the LAX→London round-trip rate, not separate awards.\n"
            "Also: Aeroplan has generally generous open-jaw and multi-city routing policies — call Aeroplan to build complex itineraries.\n"
            "Best for: Adding a Canadian city to a European or Asian trip.\n\n"
            "AMERICAN AADVANTAGE — OPEN-JAW RULES:\n"
            "AA allows true open-jaw awards at the same rate as round trips. Example: JFK→Rome (land in Rome, take a train to Barcelona), Barcelona→JFK. Pay the JFK↔Europe round-trip rate for this open-jaw.\n"
            "Also: AA allows stopovers on some international routing rules — call to build complex itineraries.\n"
            "Best for: European country-hopping without paying for an extra award segment.\n\n"
            "ALASKA MILEAGE PLAN — ROUTING RULES:\n"
            "Alaska's partner network means complex routings often require calling. Alaska generally allows the most direct routing for partner awards.\n"
            "Key limitation: Alaska awards typically require direct routing without long detours.\n\n"
            "BRITISH AIRWAYS AVIOS — ONE-WAY PRICING:\n"
            "BA prices Avios awards one-way based on distance, making round trips simply 2x one-way. This means one-way awards aren't penalized. Good for: asymmetric routing (fly one airline there, different airline back, book as separate one-way awards).\n\n"
            "ANA MILEAGE CLUB — ROUND THE WORLD:\n"
            "ANA offers Round the World awards for a fixed number of miles. Requires 3 continents, travel in one direction (no backtracking). Complex but exceptional value for true RTW trips.\n\n"
            "MULTI-CARRIER AWARD COMPLEXITY:\n"
            "Building complex multi-carrier awards requires knowing which programs can book which carriers:\n"
            "- United books Star Alliance partners (Lufthansa, ANA, Air Canada, Singapore, etc.)\n"
            "- AA books Oneworld partners (Cathay, BA, JAL, Qatar, Iberia, etc.)\n"
            "- Delta books SkyTeam partners (Air France, KLM, Korean Air, Virgin Atlantic, etc.)\n"
            "- Alaska books its unique partner network (Emirates, Cathay, JAL, BA, American)\n"
            "Each program can only book its own partners — you can't use United miles to book a BA flight (no partnership).\n\n"
            "BUILDING A COMPLEX AWARD — EXAMPLE:\n"
            "Goal: US → Tokyo (ANA) → Bali (Garuda) → Singapore (Silk Air) → US (Singapore Airlines)\n"
            "Solution: Book US→Tokyo via Virgin Atlantic (ANA sweet spot). Book Tokyo→Bali in cash (cheap). Book Bali→Singapore in cash (very cheap). Book Singapore→US via KrisFlyer or Aeroplan.\n"
            "Reality: Complex multi-carrier awards often work better as 2-3 separate one-way awards rather than one complex round-trip — more availability, more flexibility.\n\n"
            "WHEN TO CALL vs BOOK ONLINE:\n"
            "Online: Simple round-trip or one-way on a single carrier or direct partner.\n"
            "Call: Multi-city itineraries, complex routings, mixed-carrier awards, when online search shows no availability but you believe it exists."
        ),
    },
]
